/// Marketplace labels and messages; user-written names, descriptions and reviews
/// are kept in their original language when no translation key matches.
const Map<String, String> marketplaceUrduStrings = {
  'Services': 'خدمات',
  'Skilled hands. Better days.': 'ہنرمند ہاتھ۔ آسان زندگی۔',
  'Find the right help, close to home.':
      'اپنے قریب، کام کے لیے مناسب ہنرمند تلاش کریں۔',
  'YOUR NEIGHBOURHOOD': 'آپ کا علاقہ',
  'Everyday services': 'روزمرہ کی خدمات',
  'Good help for the little fixes and the bigger jobs.':
      'چھوٹی مرمت سے بڑے کام تک، مناسب مدد حاصل کریں۔',
  'Services matching your search': 'آپ کی تلاش کے مطابق خدمات',
  'Search a service or skill': 'خدمت یا مہارت تلاش کریں',
  'Clear search': 'تلاش صاف کریں',
  'Clear selection': 'انتخاب ختم کریں',
  'Looking for': 'تلاش ہے',
  'View all': 'سب دیکھیں',
  'What can we help with?': 'آپ کو کس کام میں مدد چاہیے؟',
  'From everyday fixes to bigger projects, find the right skill for the job.':
      'روزمرہ کی مرمت سے بڑے منصوبوں تک، کام کے لیے مناسب مہارت تلاش کریں۔',
  'No services match this search': 'اس تلاش کے مطابق کوئی خدمت نہیں ملی',
  'Try another skill or browse all services.':
      'دوسری مہارت تلاش کریں یا تمام خدمات دیکھیں۔',
  'Show all services': 'تمام خدمات دکھائیں',
  'Choose a skill to understand the work, then search for workers in your area.':
      'کام سمجھنے کے لیے مہارت منتخب کریں، پھر اپنے علاقے میں کاریگر تلاش کریں۔',
  'Service guide available offline. Worker profiles and bookings need a connection.':
      'خدمات کی رہنمائی آف لائن دستیاب ہے۔ کاریگر کی پروفائل اور بکنگ کے لیے کنکشن ضروری ہے۔',
  'Service details': 'خدمت کی تفصیل',
  'This service is unavailable': 'یہ خدمت دستیاب نہیں',
  'Choose the work you need': 'اپنا مطلوبہ کام منتخب کریں',
  'Pick a skill for a more focused worker search, or explore the whole profession.':
      'مناسب کاریگر تلاش کرنے کے لیے مہارت منتخب کریں یا پورا پیشہ دیکھیں۔',
  'All skills': 'تمام مہارتیں',
  'Find workers': 'کاریگر تلاش کریں',
  'You can explore every service now. Live worker search will be available when the marketplace is connected.':
      'ابھی تمام خدمات دیکھ سکتے ہیں۔ مارکیٹ پلیس کے کنکشن پر کاریگر کی تلاش دستیاب ہوگی۔',
  'Before you book': 'بکنگ سے پہلے',
  'Explain the task': 'کام کی وضاحت کریں',
  'Describe the problem, the work needed and your preferred time.':
      'مسئلہ، مطلوبہ کام اور مناسب وقت بتائیں۔',
  'Agree on the scope': 'کام کی حدود طے کریں',
  'Confirm whether the price includes the visit, labour, materials and any follow-up work.':
      'طے کریں کہ قیمت میں آنے، مزدوری، سامان اور دوبارہ کام کرنے کے اخراجات شامل ہیں یا نہیں۔',
  'Choose with confidence': 'اطمینان سے انتخاب کریں',
  'Compare real profiles, experience and completed-job reviews. Confirm the total price directly with the worker.':
      'اصل پروفائل، تجربہ اور مکمل کاموں کے جائزے دیکھیں۔ کاریگر سے براہ راست کل قیمت طے کریں۔',
  'I offer this service': 'میں یہ خدمت فراہم کرتا ہوں',
  'Explore other services': 'دیگر خدمات دیکھیں',
  'Help in your neighbourhood': 'آپ کے علاقے میں مدد',
  'Choose an area to see who can help.':
      'دستیاب کاریگر دیکھنے کے لیے علاقہ منتخب کریں۔',
  'Search within {radius} km of your location.':
      'اپنے مقام کے {radius} کلومیٹر کے اندر تلاش کریں۔',
  'Explore now. Book when connected.': 'ابھی خدمات دیکھیں، کنکشن پر بک کریں۔',
  'All services and skills are ready to browse. Live worker search and bookings are not connected yet.':
      'تمام خدمات اور مہارتیں دیکھ سکتے ہیں۔ کاریگر کی تلاش اور بکنگ ابھی منسلک نہیں ہیں۔',
  'Local help starts with your area.': 'مقامی مدد کے لیے اپنا علاقہ بتائیں۔',
  'Use your current location or choose a city. Your exact position stays private.':
      'موجودہ مقام استعمال کریں یا شہر منتخب کریں۔ آپ کا درست مقام نجی رہتا ہے۔',
  'A little help. A simple process.': 'مدد حاصل کرنے کا آسان طریقہ۔',
  'Choose a service': 'خدمت منتخب کریں',
  'Find someone nearby': 'قریبی کاریگر تلاش کریں',
  'Agree on the work': 'کام طے کریں',
  'Pick the profession and skill you need.':
      'مطلوبہ پیشہ اور مہارت منتخب کریں۔',
  'Set your area and compare genuine worker profiles.':
      'اپنا علاقہ منتخب کریں اور اصل کاریگر کی پروفائل دیکھیں۔',
  'Confirm the task, price and timing before work begins.':
      'کام شروع ہونے سے پہلے کام، قیمت اور وقت طے کریں۔',
  'FOR SKILLED WORKERS': 'ہنرمندوں کے لیے',
  'Your skills. Your next opportunity.': 'آپ کی مہارت۔ نیا موقع۔',
  'Build your profile, set your services and let local customers find your work.':
      'پروفائل بنائیں، خدمات درج کریں اور مقامی گاہکوں تک اپنا کام پہنچائیں۔',
  'Offer my services': 'اپنی خدمات پیش کریں',
  'Your contacts. Always with you.': 'آپ کے رابطے، ہمیشہ آپ کے ساتھ۔',
  'Keep personal contacts and appointment notes on this phone.':
      'ذاتی رابطے اور ملاقاتوں کے نوٹس اسی فون میں محفوظ رکھیں۔',
  'Made for the way Pakistan works.': 'پاکستان کے کام کرنے کے انداز کے مطابق۔',
  'Good help starts here': 'اچھی مدد کا آغاز یہاں سے',
  'Khidmat service professionals': 'خدمت کے ہنرمند افراد',
  'Disable push notifications': 'پش اطلاعات بند کریں',
  'Sign in to enable push notifications.': 'پش اطلاعات کے لیے سائن اِن کریں۔',
  'The push provider did not return a device token. Try again.':
      'اطلاعات کی خدمت سے آلے کا ٹوکن نہیں ملا۔ دوبارہ کوشش کریں۔',
  'Push registration needs a retry.': 'پش اطلاعات کی رجسٹریشن دوبارہ کریں۔',
  'Open notification history to refresh your latest updates.':
      'تازہ معلومات کے لیے اطلاعات کی فہرست کھولیں۔',
  'Device registration could not be fully revoked. Retry when connected.':
      'آلے کی رجسٹریشن مکمل طور پر ختم نہیں ہوئی۔ انٹرنیٹ ملنے پر دوبارہ کوشش کریں۔',
  'Push setup failed and device cleanup needs a retry when connected.':
      'پش اطلاعات کی ترتیب ناکام ہوئی۔ انٹرنیٹ ملنے پر آلے کی رجسٹریشن دوبارہ ختم کریں۔',
  'The review was hidden from public listings.':
      'جائزہ عوامی فہرست سے چھپا دیا گیا۔',
  'The review is visible again.': 'جائزہ دوبارہ دکھائی دے رہا ہے۔',
  'Explain the moderation decision in 10 to 1000 characters.':
      'فیصلے کی وجہ 10 سے 1000 حروف میں لکھیں۔',
  'Khidmat · خدمت': 'خدمت',
  'Discover': 'تلاش کریں',
  'Private organizer': 'نجی ریکارڈ',
  'Account': 'اکاؤنٹ',
  'My services': 'میری خدمات',
  'Good work. Close to home.': 'اچھا کام، آپ کے قریب۔',
  'Find skilled people for your home, your workplace and your next project.':
      'اپنے گھر، کام کی جگہ اور اگلے منصوبے کے لیے ہنرمند افراد تلاش کریں۔',
  'Choose your search location': 'تلاش کے لیے اپنا علاقہ منتخب کریں',
  'Current location': 'موجودہ مقام',
  'Manual area · distances are not shown': 'منتخب علاقہ · فاصلہ دستیاب نہیں',
  'Device location · {radius} km radius':
      'موجودہ مقام · {radius} کلومیٹر کا دائرہ',
  'Where do you need help?': 'آپ کو کہاں مدد چاہیے؟',
  'Device location finds workers within your search radius. You can also browse a city without sharing your location.':
      'موجودہ مقام سے مقررہ دائرے میں کاریگر ملتے ہیں۔ مقام شیئر کیے بغیر شہر بھی منتخب کر سکتے ہیں۔',
  'Use my current location': 'میرا موجودہ مقام استعمال کریں',
  'Open app location settings': 'ایپ کی مقام کی ترتیبات کھولیں',
  'Neighbourhood (optional)': 'محلہ یا علاقہ (اختیاری)',
  'Search this area': 'اس علاقے میں تلاش کریں',
  'Choose location': 'علاقہ منتخب کریں',
  'Choose location or retry': 'علاقہ منتخب کریں یا دوبارہ کوشش کریں',
  'Device location is not shared. You can still choose a city and neighbourhood.':
      'موجودہ مقام شیئر نہیں ہوا۔ آپ شہر اور محلہ منتخب کر سکتے ہیں۔',
  'Location services are switched off. You can choose a city or enable device location.':
      'مقام کی سہولت بند ہے۔ شہر منتخب کریں یا مقام کی سہولت کھولیں۔',
  'The marketplace is not connected yet. Live service categories, workers, verified sign-in and job requests will become available after setup. Your saved phone records remain available.':
      'آن لائن خدمت ابھی منسلک نہیں۔ ترتیب مکمل ہونے پر خدمات، کاریگر، تصدیق شدہ سائن اِن اور کام کی درخواستیں دستیاب ہوں گی۔ فون پر محفوظ ریکارڈ استعمال کر سکتے ہیں۔',
  'Search profession, service or skill': 'پیشہ، خدمت یا ہنر تلاش کریں',
  'Search filters': 'تلاش کے فلٹر',
  'Explore services': 'خدمات دیکھیں',
  'Choose a category, a profession, then a skill.':
      'پہلے شعبہ، پھر پیشہ اور ہنر منتخب کریں۔',
  'All services': 'تمام خدمات',
  '{profession} specializations': '{profession} کی مہارتیں',
  'Workers near you': 'آپ کے قریب کاریگر',
  'Workers in your area': 'آپ کے علاقے کے کاریگر',
  'Recently available workers': 'حال ہی میں دستیابی بتانے والے کاریگر',
  'Compare services, availability and starting prices.':
      'خدمات، دستیابی اور ابتدائی قیمتوں کا موازنہ کریں۔',
  'Filter workers': 'کاریگروں کے فلٹر',
  'Start with your area': 'اپنا علاقہ منتخب کریں',
  'Choose a city or use your current location to discover local workers.':
      'مقامی کاریگر تلاش کرنے کے لیے شہر یا موجودہ مقام منتخب کریں۔',
  'No matching workers yet': 'ابھی کوئی موزوں کاریگر نہیں ملا',
  'Try another profession, a wider radius or fewer filters. Only published eligible profiles appear here.':
      'دوسرا پیشہ، بڑا دائرہ یا کم فلٹر آزمائیں۔ یہاں صرف اہل اور شائع شدہ پروفائل نظر آتے ہیں۔',
  'Load more workers': 'مزید کاریگر دکھائیں',
  'Put your skills to work': 'اپنے ہنر سے کام حاصل کریں',
  'Create one profile and choose your profession and skills.':
      'ایک پروفائل بنائیں اور اپنا پیشہ اور ہنر منتخب کریں۔',
  'Find the right worker': 'مناسب کاریگر تلاش کریں',
  'Search radius: {radius} km': 'تلاش کا دائرہ: {radius} کلومیٹر',
  'A distance and radius are available with device coordinates. Manual location searches match the selected city and neighbourhood.':
      'موجودہ مقام کے ساتھ فاصلہ اور دائرہ استعمال ہوتے ہیں۔ دستی انتخاب میں منتخب شہر اور محلے کے مطابق تلاش ہوتی ہے۔',
  'Sort workers': 'کاریگروں کی ترتیب',
  'Nearest': 'سب سے قریب',
  'Highest rated': 'سب سے اچھی ریٹنگ',
  'Lowest starting price': 'سب سے کم ابتدائی قیمت',
  'Most experienced': 'سب سے زیادہ تجربہ',
  'Min price (PKR)': 'کم سے کم قیمت (روپے)',
  'Max price (PKR)': 'زیادہ سے زیادہ قیمت (روپے)',
  'Maximum must be at least the minimum.':
      'زیادہ سے زیادہ قیمت کم سے کم قیمت سے کم نہیں ہو سکتی۔',
  'Compare prices with the same pricing unit on worker profiles.':
      'کاریگروں کی قیمتوں کا موازنہ ایک ہی طریقۂ قیمت کے مطابق کریں۔',
  'Minimum rating: {rating}': 'کم سے کم ریٹنگ: {rating}',
  'Minimum experience: {years} years': 'کم سے کم تجربہ: {years} سال',
  'Available now only': 'صرف ابھی دستیاب',
  'Requires a recent availability update.': 'دستیابی کی حالیہ تصدیق ضروری ہے۔',
  'Apply filters': 'فلٹر لگائیں',
  'Available now': 'ابھی دستیاب',
  'Available later': 'بعد میں دستیاب',
  'Busy': 'مصروف',
  'Offline': 'آف لائن',
  'Availability unknown': 'دستیابی معلوم نہیں',
  '{years} years experience': '{years} سال کا تجربہ',
  'About {distance} km away · {city}':
      'تقریباً {distance} کلومیٹر دور · {city}',
  'About {distance} km away': 'تقریباً {distance} کلومیٹر دور',
  'No reviews yet': 'ابھی کوئی رائے نہیں',
  'Price by agreement': 'قیمت باہمی اتفاق سے',
  'From PKR {price} / {unit}': 'ابتدائی قیمت {price} روپے / {unit}',
  'Welcome to Khidmat': 'خدمت میں خوش آمدید',
  'Your next good connection': 'اچھے کام کے لیے ایک نیا رابطہ',
  'Check your messages': 'اپنے پیغامات دیکھیں',
  'Use your Pakistani mobile number to create an account or sign in. We verify it with a code sent by SMS.':
      'اکاؤنٹ بنانے یا سائن اِن کرنے کے لیے اپنا پاکستانی موبائل نمبر استعمال کریں۔ ایس ایم ایس کوڈ سے نمبر کی تصدیق ہوتی ہے۔',
  'Phone sign-in will be available after the marketplace is connected. Your saved phone records remain available.':
      'آن لائن خدمت منسلک ہونے کے بعد فون سے سائن اِن دستیاب ہوگا۔ آپ کے فون پر محفوظ ریکارڈ دستیاب ہیں۔',
  'Pakistani mobile number': 'پاکستانی موبائل نمبر',
  'Verification code': 'تصدیقی کوڈ',
  'Enter the 6-digit code from your SMS.':
      'ایس ایم ایس سے موصول ہونے والا 6 ہندسوں کا کوڈ درج کریں۔',
  'Verify and continue': 'تصدیق کریں اور آگے بڑھیں',
  'Send verification code': 'تصدیقی کوڈ بھیجیں',
  'Resend code in {seconds} seconds': '{seconds} سیکنڈ بعد دوبارہ کوڈ بھیجیں',
  'Resend code': 'کوڈ دوبارہ بھیجیں',
  'Change phone number': 'فون نمبر تبدیل کریں',
  'Sign in with phone': 'فون نمبر سے سائن اِن کریں',
  'Sign in to continue.': 'آگے بڑھنے کے لیے سائن اِن کریں۔',
  'Lost access? You can sign in again with the same verified number. If you no longer own the number, contact support before creating a replacement account.':
      'رسائی ختم ہو گئی؟ اسی تصدیق شدہ نمبر سے دوبارہ سائن اِن کریں۔ اگر نمبر آپ کے پاس نہیں رہا تو نیا اکاؤنٹ بنانے سے پہلے معاونت سے رابطہ کریں۔',
  'My account': 'میرا اکاؤنٹ',
  'Your account is restricted. You can browse services, but marketplace actions are unavailable.':
      'آپ کا اکاؤنٹ محدود ہے۔ خدمات دیکھ سکتے ہیں لیکن کام کی درخواست اور دیگر کارروائیاں دستیاب نہیں۔',
  'View account status': 'اکاؤنٹ کی حالت دیکھیں',
  'Sign in to manage your account and job history.':
      'اپنا اکاؤنٹ اور کام کی تاریخ دیکھنے کے لیے سائن اِن کریں۔',
  'Your phone is verified. Add your name, city and how you want to use Khidmat. You can finish your worker profile later.':
      'آپ کے فون کی تصدیق ہو گئی۔ نام، شہر اور خدمت استعمال کرنے کا طریقہ شامل کریں۔ پیشہ ورانہ پروفائل بعد میں مکمل کر سکتے ہیں۔',
  'Full name': 'پورا نام',
  'WhatsApp number (if different)': 'واٹس ایپ نمبر (اگر مختلف ہے)',
  'You can request work and offer services with the same account.':
      'ایک ہی اکاؤنٹ سے کام کی درخواست اور اپنی خدمات پیش کر سکتے ہیں۔',
  'Save account': 'اکاؤنٹ محفوظ کریں',
  'Account saved.': 'اکاؤنٹ محفوظ ہو گیا۔',
  'My professional profile': 'میری پیشہ ورانہ پروفائل',
  'Services, prices, schedule and availability':
      'خدمات، قیمتیں، اوقات اور دستیابی',
  'My job history': 'میرے کام کی تاریخ',
  'Privacy and account data': 'رازداری اور اکاؤنٹ کا ڈیٹا',
  'Help and safety': 'مدد اور حفاظت',
  'Administration': 'انتظامیہ',
  'Log out': 'لاگ آؤٹ کریں',
  'Sign in to offer your services and receive job requests.':
      'اپنی خدمات پیش کرنے اور کام کی درخواستیں وصول کرنے کے لیے سائن اِن کریں۔',
  'Account restricted': 'اکاؤنٹ محدود ہے',
  'Step {step} of 4': 'مرحلہ {step} از 4',
  'First, introduce yourself': 'پہلے اپنا تعارف کروائیں',
  'Your account is already created. You can save a draft before publishing your services.':
      'آپ کا اکاؤنٹ بن چکا ہے۔ خدمات شائع کرنے سے پہلے مسودہ محفوظ کر سکتے ہیں۔',
  'Verified account phone number': 'اکاؤنٹ کا تصدیق شدہ فون نمبر',
  'Neighbourhood / service area': 'محلہ / کام کا علاقہ',
  'Use an area name, not your home address. Customers see your service area and approximate distance, never your precise coordinates.':
      'اپنا علاقہ لکھیں، گھر کا پتہ نہیں۔ گاہک کو کام کا علاقہ اور اندازاً فاصلہ نظر آتا ہے، درست جغرافیائی مقام نہیں۔',
  'Show what you do best': 'اپنی مہارت بتائیں',
  'Your profession determines the skills and questions below.':
      'آپ کے پیشے کے مطابق نیچے ہنر اور سوالات دکھائے جاتے ہیں۔',
  'Choose your profession.': 'اپنا پیشہ منتخب کریں۔',
  'Skills and specializations': 'ہنر اور خصوصی مہارتیں',
  'Years of experience': 'تجربے کے سال',
  'Enter experience from 0 to 60 years.': 'صفر سے 60 سال تک تجربہ درج کریں۔',
  'About your work': 'آپ کے کام کے بارے میں',
  'Describe your experience and the work you can take on.':
      'اپنا تجربہ اور وہ کام بتائیں جو آپ کر سکتے ہیں۔',
  'Languages (comma separated)': 'زبانیں (کوما سے الگ کریں)',
  'Urdu, Punjabi, English': 'اردو، پنجابی، انگریزی',
  'Set your price and working hours': 'قیمت اور کام کے اوقات مقرر کریں',
  'Starting price (PKR)': 'ابتدائی قیمت (روپے)',
  'Pricing method': 'قیمت کا طریقہ',
  'Per hour': 'فی گھنٹہ',
  'Per day': 'فی دن',
  'Per job': 'فی کام',
  'Per visit': 'فی وزٹ',
  'hour': 'گھنٹہ',
  'day': 'دن',
  'job': 'کام',
  'visit': 'وزٹ',
  'Service radius: {radius} km': 'کام کا دائرہ: {radius} کلومیٹر',
  'Working days': 'کام کے دن',
  'Mon': 'پیر',
  'Tue': 'منگل',
  'Wed': 'بدھ',
  'Thu': 'جمعرات',
  'Fri': 'جمعہ',
  'Sat': 'ہفتہ',
  'Sun': 'اتوار',
  'Start: {time}': 'شروع: {time}',
  'Finish: {time}': 'اختتام: {time}',
  'Your working hours describe your usual schedule. Set your current availability separately after saving your profile.':
      'یہ اوقات آپ کا معمول کا شیڈول ہیں۔ پروفائل محفوظ کرنے کے بعد موجودہ دستیابی الگ مقرر کریں۔',
  'Add your work. Make it yours.': 'اپنے کام کی تصاویر شامل کریں',
  'Photos are optional. Upload only images you have permission to share.':
      'تصاویر اختیاری ہیں۔ صرف وہ تصاویر شامل کریں جنہیں شیئر کرنے کی اجازت آپ کے پاس ہو۔',
  'Profile photo': 'پروفائل تصویر',
  'Portfolio photos': 'پچھلے کام کی تصاویر',
  'Remove image': 'تصویر ہٹائیں',
  'Let signed-in customers contact me': 'سائن اِن گاہک مجھ سے رابطہ کر سکیں',
  'Share your phone and WhatsApp number when an eligible customer asks. Job requests work without sharing these details.':
      'اہل گاہک کی درخواست پر فون اور واٹس ایپ نمبر شیئر کریں۔ نمبر شیئر کیے بغیر بھی کام کی درخواستیں وصول ہوتی ہیں۔',
  'Public profile preview': 'عوامی پروفائل کا پیش منظر',
  'Publishing makes your profile discoverable. A draft stays private. To publish, add skills, a description of at least 20 characters, a price and working days, and complete the questions for your profession.':
      'شائع ہونے پر گاہک آپ کی پروفائل تلاش کر سکتے ہیں۔ مسودہ نجی رہتا ہے۔ شائع کرنے کے لیے ہنر، کم از کم 20 حروف کا تعارف، قیمت، کام کے دن اور پیشے کے سوالات مکمل کریں۔',
  'Continue': 'آگے بڑھیں',
  'Back': 'واپس',
  'Publish profile': 'پروفائل شائع کریں',
  'Save draft': 'مسودہ محفوظ کریں',
  'Worker draft saved.': 'پیشہ ورانہ مسودہ محفوظ ہو گیا۔',
  'Your professional profile is published.':
      'آپ کی پیشہ ورانہ پروفائل شائع ہو گئی۔',
  'Current availability': 'موجودہ دستیابی',
  'Update this when you can accept work. Available now expires after 15 minutes.':
      'جب کام قبول کر سکیں تو اسے تبدیل کریں۔ ابھی دستیاب کی حالت 15 منٹ بعد ختم ہو جاتی ہے۔',
  'Share your service location?': 'کام کے لیے اپنا موجودہ مقام شیئر کریں؟',
  'Available now uses your current device location to match nearby customers. Your exact coordinates stay private. Location is updated only when you choose this action.':
      'ابھی دستیاب کی حالت قریبی گاہک ملانے کے لیے موجودہ مقام استعمال کرتی ہے۔ درست مقام نجی رہتا ہے اور صرف آپ کے انتخاب پر تبدیل ہوتا ہے۔',
  'Use location': 'مقام استعمال کریں',
  'View published profile': 'شائع شدہ پروفائل دیکھیں',
  'Worker profile': 'کاریگر کی پروفائل',
  'Refresh profile': 'پروفائل تازہ کریں',
  'Profile unavailable': 'پروفائل دستیاب نہیں',
  'Worker check completed': 'کاریگر کی جانچ مکمل',
  'Service area only · distance unavailable':
      'صرف کام کا علاقہ · فاصلہ دستیاب نہیں',
  'Confirm the final scope and price before work begins.':
      'کام شروع ہونے سے پہلے تفصیل اور آخری قیمت طے کریں۔',
  '{rating} from {count} reviews': '{count} آراء سے {rating} ریٹنگ',
  'About this worker': 'اس کاریگر کے بارے میں',
  'No description provided.': 'تعارف شامل نہیں کیا گیا۔',
  'Languages: {languages}': 'زبانیں: {languages}',
  'Working hours: {start} – {end}': 'کام کے اوقات: {start} تا {end}',
  'Previous work': 'پچھلا کام',
  'Request work': 'کام کی درخواست دیں',
  'This worker is not currently accepting requests. Check back later.':
      'یہ کاریگر ابھی درخواستیں قبول نہیں کر رہا۔ بعد میں دوبارہ دیکھیں۔',
  'WhatsApp': 'واٹس ایپ',
  'Report profile': 'پروفائل کی شکایت کریں',
  'Reviews from completed jobs': 'مکمل کاموں کی آراء',
  'This worker has no published reviews yet.':
      'اس کاریگر کے بارے میں ابھی کوئی شائع شدہ رائے نہیں۔',
  'Availability can change. A profile or phone call does not guarantee a booking. Never share verification codes or pay an unexpected advance to an unverified person.':
      'دستیابی بدل سکتی ہے۔ پروفائل یا فون کال سے بکنگ یقینی نہیں ہوتی۔ تصدیقی کوڈ کسی کو نہ دیں اور نامعلوم شخص کو غیر متوقع پیشگی رقم ادا نہ کریں۔',
  'A request is confirmed when the worker accepts. Agree on the final scope, price and materials before work begins.':
      'کاریگر کے قبول کرنے پر درخواست کی تصدیق ہوتی ہے۔ کام سے پہلے تفصیل، قیمت اور سامان طے کریں۔',
  'Describe the work': 'کام کی تفصیل',
  'Describe the work in at least 10 characters.':
      'کم از کم 10 حروف میں کام کی تفصیل لکھیں۔',
  'Neighbourhood': 'محلہ یا علاقہ',
  'Work address (private)': 'کام کا پتہ (نجی)',
  'Shared only with this job’s participants':
      'صرف اس کام میں شامل افراد کے ساتھ شیئر ہوتا ہے',
  'Your offered price (PKR, optional)': 'آپ کی پیش کردہ قیمت (روپے، اختیاری)',
  'Requested date and time': 'درخواست کی تاریخ اور وقت',
  'Choose a future date and time.': 'آنے والی تاریخ اور وقت منتخب کریں۔',
  'Send job request': 'کام کی درخواست بھیجیں',
  'Sending request…': 'درخواست بھیجی جا رہی ہے…',
  'Job request sent.': 'کام کی درخواست بھیج دی گئی۔',
  'Report this profile': 'اس پروفائل کی شکایت کریں',
  'Reason': 'وجہ',
  'What happened?': 'کیا ہوا؟',
  'Add at least 10 characters.': 'کم از کم 10 حروف لکھیں۔',
  'Submit report': 'شکایت بھیجیں',
  'Submitting…': 'بھیجا جا رہا ہے…',
  'Report submitted for review.': 'شکایت جائزے کے لیے بھیج دی گئی۔',
  'Safety concern': 'حفاظت کا مسئلہ',
  'Fraud or scam': 'دھوکا دہی',
  'Harassment': 'ہراسانی',
  'Inappropriate profile': 'نامناسب پروفائل',
  'Other': 'دیگر',
  'My jobs': 'میرے کام',
  'Sign in to see requests, bookings and completed jobs.':
      'درخواستیں، بکنگ اور مکمل کام دیکھنے کے لیے سائن اِن کریں۔',
  'Every job, in one place': 'تمام کام ایک جگہ',
  'Requests are confirmed when the worker accepts. Customers confirm completed work.':
      'کاریگر کے قبول کرنے پر درخواست کی تصدیق ہوتی ہے۔ گاہک مکمل کام کی تصدیق کرتے ہیں۔',
  'As customer': 'بطور گاہک',
  'As worker': 'بطور کاریگر',
  'No jobs here yet': 'ابھی یہاں کوئی کام نہیں',
  'Find a worker to request a service, or publish your professional profile to receive work.':
      'خدمت کی درخواست کے لیے کاریگر تلاش کریں یا کام حاصل کرنے کے لیے اپنی پروفائل شائع کریں۔',
  'Load more jobs': 'مزید کام دکھائیں',
  'Awaiting worker response': 'کاریگر کے جواب کا انتظار',
  'Booking confirmed': 'بکنگ کی تصدیق ہو گئی',
  'Work in progress': 'کام جاری ہے',
  'Completion awaiting confirmation': 'تکمیل کی تصدیق کا انتظار',
  'Declined': 'درخواست مسترد',
  'Status unavailable': 'حالت دستیاب نہیں',
  'Accept request': 'درخواست قبول کریں',
  'Decline request': 'درخواست مسترد کریں',
  'Mark in progress': 'کام جاری قرار دیں',
  'Request completion': 'تکمیل کی تصدیق مانگیں',
  'Confirm completed': 'مکمل کام کی تصدیق کریں',
  'Cancel job': 'کام منسوخ کریں',
  'Confirm completed work?': 'مکمل کام کی تصدیق کریں؟',
  'Confirm only after the agreed work has been completed. You can leave a review afterwards.':
      'طے شدہ کام مکمل ہونے کے بعد تصدیق کریں۔ اس کے بعد اپنی رائے دے سکتے ہیں۔',
  'The other participant will be notified of this change.':
      'دوسرے فریق کو اس تبدیلی کی اطلاع دی جائے گی۔',
  'Review this completed job': 'اس مکمل کام کے بارے میں رائے دیں',
  'How was the work?': 'کام کیسا رہا؟',
  'stars': 'ستارے',
  'Your review (optional)': 'آپ کی رائے (اختیاری)',
  'Share your experience with the work. Keep phone numbers and private addresses out of your review.':
      'کام کے بارے میں اپنا تجربہ بتائیں۔ رائے میں فون نمبر یا نجی پتے شامل نہ کریں۔',
  'Submit review': 'رائے بھیجیں',
  'Your service request': 'آپ کی کام کی درخواست',
  'Customer request': 'گاہک کی درخواست',
  'Private job address · shared with participants only':
      'نجی کام کا پتہ · صرف متعلقہ افراد کے لیے',
  'Price to be agreed': 'قیمت طے کرنا باقی ہے',
  'Offered price: PKR {price}': 'پیش کردہ قیمت: {price} روپے',
  'The worker has requested completion. Confirm the work is done, or return it to in progress.':
      'کاریگر نے تکمیل کی تصدیق مانگی ہے۔ کام مکمل ہونے کی تصدیق کریں یا اسے دوبارہ جاری قرار دیں۔',
  'Waiting for the customer to confirm completion.':
      'گاہک کی طرف سے تکمیل کی تصدیق کا انتظار ہے۔',
  'Leave a review': 'اپنی رائے دیں',
  'Your review has been submitted.': 'آپ کی رائے بھیج دی گئی۔',
  'View worker profile': 'کاریگر کی پروفائل دیکھیں',
  'Notifications': 'اطلاعات',
  'Sign in to see updates about your jobs.':
      'اپنے کام کی تازہ اطلاعات دیکھنے کے لیے سائن اِن کریں۔',
  'Stay up to date': 'تازہ صورتحال جانیں',
  'Request responses, job progress and new reviews.':
      'درخواستوں کے جواب، کام کی پیش رفت اور نئی آراء۔',
  'In-app updates refresh while Khidmat is open. Pull down to check again.':
      'خدمت کھلی ہونے پر اطلاعات تازہ ہوتی ہیں۔ دوبارہ دیکھنے کے لیے نیچے کھینچیں۔',
  'Push notifications': 'فون پر اطلاعات',
  'Receive job updates when Khidmat is closed.':
      'خدمت بند ہونے پر بھی کام کی اطلاعات وصول کریں۔',
  'Push notifications require provider setup. In-app notification history remains available.':
      'فون پر اطلاعات کے لیے سروس کی ترتیب ضروری ہے۔ ایپ میں اطلاعات کی تاریخ دستیاب رہتی ہے۔',
  'You are all caught up': 'آپ نے تمام اطلاعات دیکھ لی ہیں',
  'Updates about your requests and bookings will appear here.':
      'آپ کی درخواستوں اور بکنگ کی اطلاعات یہاں نظر آئیں گی۔',
  'Load more notifications': 'مزید اطلاعات دکھائیں',
  'You decide what you share': 'آپ طے کریں کہ کیا شیئر کرنا ہے',
  'Device location is requested only when you choose to use it. Khidmat does not continuously track you in the background.':
      'موجودہ مقام صرف آپ کے انتخاب پر مانگا جاتا ہے۔ خدمت پس منظر میں مسلسل آپ کی نگرانی نہیں کرتی۔',
  'Your public worker profile': 'آپ کی عوامی پیشہ ورانہ پروفائل',
  'Customers can see your professional name, service area, skills, prices, working hours, portfolio and completed-job reviews when your profile is published. Upload photos and write descriptions that you are comfortable making public.':
      'شائع شدہ پروفائل میں گاہک آپ کا نام، کام کا علاقہ، ہنر، قیمتیں، اوقات، تصاویر اور مکمل کاموں کی آراء دیکھ سکتے ہیں۔ صرف وہ تصاویر اور تفصیلات شامل کریں جو آپ عوامی کرنا چاہتے ہیں۔',
  'Your location and contact details': 'آپ کا مقام اور رابطے کی تفصیلات',
  'Your exact worker coordinates are kept private. Customers see an approximate distance when a sufficiently recent service location is available. Your home address is not part of your public profile. Phone and WhatsApp details are shared with eligible signed-in customers only if you enable contact sharing.':
      'آپ کا درست مقام نجی رہتا ہے۔ حالیہ مقام دستیاب ہونے پر گاہک اندازاً فاصلہ دیکھتے ہیں۔ گھر کا پتہ عوامی پروفائل کا حصہ نہیں۔ فون اور واٹس ایپ صرف آپ کی اجازت سے اہل سائن اِن گاہک کو دیے جاتے ہیں۔',
  'Manage my public profile and contact sharing':
      'عوامی پروفائل اور رابطہ شیئر کرنے کی ترتیب',
  'Job details and reviews': 'کام کی تفصیل اور آراء',
  'Your private work address and job details are accessible to the job’s participants. Reviews are public. Keep personal phone numbers, identity documents and private addresses out of reviews.':
      'کام کا نجی پتہ اور تفصیلات صرف متعلقہ فریق دیکھ سکتے ہیں۔ آراء عوامی ہوتی ہیں۔ ان میں ذاتی نمبر، شناختی دستاویزات یا نجی پتے شامل نہ کریں۔',
  'Sign in to export your account data or manage your account.':
      'اکاؤنٹ سنبھالنے یا ڈیٹا کی کاپی لینے کے لیے سائن اِن کریں۔',
  'Your account data': 'آپ کے اکاؤنٹ کا ڈیٹا',
  'Export a copy of your profile, job records, reviews and reports. The exported file contains personal information; choose a private destination.':
      'اپنی پروفائل، کام، آراء اور شکایات کی کاپی حاصل کریں۔ اس فائل میں ذاتی معلومات ہوتی ہیں؛ نجی جگہ منتخب کریں۔',
  'Preparing export…': 'ڈیٹا تیار ہو رہا ہے…',
  'Export my account data': 'میرے اکاؤنٹ کا ڈیٹا حاصل کریں',
  'My Khidmat account data': 'میرے خدمت اکاؤنٹ کا ڈیٹا',
  'Deactivate your account': 'اپنا اکاؤنٹ غیر فعال کریں',
  'Deactivation hides your worker profile, cancels pending requests, removes your saved service coordinates and signs you out. Resolve accepted or ongoing work first. Job history and account records are retained; this does not delete your data. Contact support about data removal or reactivation.':
      'غیر فعال کرنے سے پروفائل چھپ جاتی ہے، زیرِ التوا درخواستیں منسوخ ہوتی ہیں، محفوظ مقام ہٹتا ہے اور آپ سائن آؤٹ ہو جاتے ہیں۔ پہلے قبول شدہ یا جاری کام نمٹائیں۔ تاریخ اور اکاؤنٹ کا ریکارڈ برقرار رہتا ہے؛ ڈیٹا حذف نہیں ہوتا۔ ڈیٹا ہٹانے یا بحالی کے لیے معاونت سے رابطہ کریں۔',
  'Deactivate your account?': 'اپنا اکاؤنٹ غیر فعال کریں؟',
  'Your profile will be hidden and pending requests cancelled. Your account records and job history will be retained.':
      'پروفائل چھپ جائے گی اور زیرِ التوا درخواستیں منسوخ ہوں گی۔ اکاؤنٹ کا ریکارڈ اور کام کی تاریخ برقرار رہے گی۔',
  'Deactivate account': 'اکاؤنٹ غیر فعال کریں',
  'Contact support and get help': 'معاونت سے رابطہ کریں',
  'Find local help': 'مقامی مدد تلاش کریں',
  'Choose your city or use device location, then select a profession and skill. Compare experience, prices, availability and reviews. Send a request with the work details and a proposed time.':
      'شہر یا موجودہ مقام کے بعد پیشہ اور ہنر منتخب کریں۔ تجربے، قیمت، دستیابی اور آراء کا موازنہ کریں۔ تفصیل اور مجوزہ وقت کے ساتھ کام کی درخواست بھیجیں۔',
  'The worker must accept your request to confirm the booking. Agree on the scope, materials and final price directly. A starting price is an estimate for the stated pricing unit.':
      'بکنگ کی تصدیق کے لیے کاریگر کا قبول کرنا ضروری ہے۔ کام، سامان اور آخری قیمت براہِ راست طے کریں۔ ابتدائی قیمت بتائے گئے طریقۂ قیمت کے مطابق تخمینہ ہے۔',
  'Offer your services': 'اپنی خدمات پیش کریں',
  'Verify your mobile number, complete your account details and add the worker role. Build your professional profile in four steps. You can save a private draft and return later. Publish your profile when the required details are ready.':
      'موبائل کی تصدیق، اکاؤنٹ کی تفصیل اور کاریگر کا کردار شامل کریں۔ چار مراحل میں پروفائل بنائیں۔ نجی مسودہ محفوظ کرکے بعد میں واپس آ سکتے ہیں۔ ضروری تفصیلات مکمل ہونے پر شائع کریں۔',
  'Keep your availability accurate': 'اپنی دستیابی درست رکھیں',
  'Available now requires a recent location update and expires after 15 minutes. Choose Available later, Busy or Offline when appropriate. Your usual working schedule is separate from your current availability.':
      'ابھی دستیاب کے لیے حالیہ مقام ضروری ہے اور یہ حالت 15 منٹ بعد ختم ہوتی ہے۔ ضرورت کے مطابق بعد میں دستیاب، مصروف یا آف لائن منتخب کریں۔ معمول کا شیڈول موجودہ دستیابی سے الگ ہے۔',
  'Complete and review': 'کام مکمل کریں اور رائے دیں',
  'Workers update the job as work progresses and request completion. The customer confirms completion, then can leave one review for that job.':
      'کاریگر کام کی پیش رفت بتاتے اور تکمیل کی درخواست کرتے ہیں۔ گاہک تکمیل کی تصدیق کے بعد اس کام پر ایک رائے دے سکتا ہے۔',
  'Stay safe': 'محفوظ رہیں',
  'Keep verification codes private. Confirm who you are dealing with and discuss the work before paying. Use Report profile to send a concern to the operator. A verified phone number is not proof of identity or qualifications.':
      'تصدیقی کوڈ نجی رکھیں۔ ادائیگی سے پہلے دوسرے شخص اور کام کی تفصیل کی تصدیق کریں۔ مسئلے پر پروفائل کی شکایت بھیجیں۔ تصدیق شدہ فون شناخت یا قابلیت کا ثبوت نہیں۔',
  'Contact support': 'معاونت سے رابطہ کریں',
  'A support contact has not been configured for this installation. Profile reports are stored for review when the marketplace is connected.':
      'اس تنصیب میں معاونت کا رابطہ مقرر نہیں۔ آن لائن خدمت منسلک ہونے پر پروفائل کی شکایات جائزے کے لیے محفوظ ہوتی ہیں۔',
  'Saved phone records': 'فون پر محفوظ ریکارڈ',
  'Your older contacts and appointment notes stay in Saved records. These records are separate from online bookings and do not notify other people.':
      'آپ کے پرانے رابطے اور ملاقاتوں کے نوٹس محفوظ ریکارڈ میں رہتے ہیں۔ یہ آن لائن بکنگ سے الگ ہیں اور دوسرے افراد کو اطلاع نہیں دیتے۔',
  'Administrator access required': 'منتظم کی رسائی درکار ہے',
  'This account cannot access moderation tools.':
      'اس اکاؤنٹ کو انتظامی سہولتوں کی اجازت نہیں۔',
  'Sign in with an administrator account to continue.':
      'آگے بڑھنے کے لیے منتظم کے اکاؤنٹ سے سائن اِن کریں۔',
  'Reported accounts': 'جن اکاؤنٹس کی شکایت ہوئی',
  'Review the evidence before applying a decision. Every decision is recorded.':
      'فیصلہ کرنے سے پہلے شواہد دیکھیں۔ ہر فیصلہ ریکارڈ ہوتا ہے۔',
  'No reports to display': 'دکھانے کے لیے کوئی شکایت نہیں',
  'Reports submitted by customers and workers appear here.':
      'گاہکوں اور کاریگروں کی شکایات یہاں نظر آتی ہیں۔',
  'Record a decision': 'فیصلہ درج کریں',
  'Review moderation': 'آراء کا جائزہ',
  'Original review text and ratings are retained. Hidden reviews do not contribute to public ratings.':
      'اصل رائے اور ریٹنگ محفوظ رہتی ہے۔ چھپائی گئی آراء عوامی ریٹنگ میں شامل نہیں ہوتیں۔',
  'No reviews to moderate': 'جائزے کے لیے کوئی رائے نہیں',
  'Hide review': 'رائے چھپائیں',
  'Restore review': 'رائے بحال کریں',
  'Review hidden': 'رائے چھپا دی گئی',
  'Review visible': 'رائے نظر آ رہی ہے',
  'Review ID': 'رائے کی شناخت',
  'Worker ID': 'کاریگر کی شناخت',
  'Customer ID': 'گاہک کی شناخت',
  'Load more reviews': 'مزید آراء دکھائیں',
  'Load more reports': 'مزید شکایات دکھائیں',
  'Hide this review?': 'یہ رائے چھپائیں؟',
  'Restore this review?': 'یہ رائے بحال کریں؟',
  'Record at least 10 characters explaining this decision.':
      'اس فیصلے کی وضاحت کم از کم 10 حروف میں لکھیں۔',
  'Decision reason': 'فیصلے کی وجہ',
  'Save decision': 'فیصلہ محفوظ کریں',
  'Account ID': 'اکاؤنٹ کی شناخت',
  'Enter a valid account ID.': 'اکاؤنٹ کی درست شناخت درج کریں۔',
  'Moderation action': 'انتظامی کارروائی',
  'Evidence and decision reason': 'شواہد اور فیصلے کی وجہ',
  'Apply decision': 'فیصلہ نافذ کریں',
  'Apply moderation decision?': 'انتظامی فیصلہ نافذ کریں؟',
  'Suspend account': 'اکاؤنٹ معطل کریں',
  'Reactivate account': 'اکاؤنٹ بحال کریں',
  'Verify worker': 'کاریگر کی تصدیق کریں',
  'Revoke worker verification': 'کاریگر کی تصدیق واپس لیں',
  'Worker verification is an operator decision based on evidence. A verified phone number alone does not verify a worker’s identity or qualifications.':
      'کاریگر کی تصدیق شواہد کی بنیاد پر منتظم کا فیصلہ ہے۔ صرف تصدیق شدہ فون سے شناخت یا قابلیت ثابت نہیں ہوتی۔',
  'Enter at least 2 characters.': 'کم از کم 2 حروف درج کریں۔',
  'Enter a Pakistani mobile number, e.g. 0300 1234567.':
      'پاکستانی موبائل نمبر درج کریں، مثلاً 0300 1234567۔',
  'Enter a valid Pakistani mobile number.':
      'درست پاکستانی موبائل نمبر درج کریں۔',
  'Enter a number from 0 to {max}.': 'صفر سے {max} تک عدد درج کریں۔',
  'Choose an image smaller than 5 MB.': '5 ایم بی سے چھوٹی تصویر منتخب کریں۔',
  'Too many attempts. Wait a little and try again.':
      'بہت زیادہ کوششیں ہو چکیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔',
  'Phone verification is not available. Check the SMS provider configuration.':
      'فون کی تصدیق دستیاب نہیں۔ سروس کی ترتیب کی جانچ ضروری ہے۔',
  'This verification code is invalid or expired. Request a new code.':
      'یہ کوڈ غلط یا زائد المیعاد ہے۔ نیا کوڈ منگوائیں۔',
  'The marketplace database has not been set up for this app version.':
      'اس ایپ کے لیے آن لائن سروس کی ترتیب مکمل نہیں۔',
  'You do not have permission to perform this action.':
      'آپ کو اس کارروائی کی اجازت نہیں۔',
  'The service could not be reached. Check your connection and try again.':
      'سروس سے رابطہ نہیں ہو سکا۔ انٹرنیٹ دیکھ کر دوبارہ کوشش کریں۔',
  'Wait a minute before requesting another code.':
      'دوبارہ کوڈ مانگنے سے پہلے ایک منٹ انتظار کریں۔',
  'Construction': 'تعمیرات',
  'Electrical Services': 'بجلی کی خدمات',
  'Plumbing Services': 'پلمبنگ کی خدمات',
  'Home Services': 'گھریلو خدمات',
  'Appliance Services': 'آلات کی مرمت',
  'Outdoor Services': 'بیرونی خدمات',
  'Learning Services': 'تعلیمی خدمات',
  'Personal Services': 'ذاتی خدمات',
  'Other Services': 'دیگر خدمات',
  'Mazdoor': 'مزدور',
  'Mason': 'مستری',
  'Welder': 'ویلڈر',
  'Tile Installer': 'ٹائل لگانے والا',
  'Cleaner': 'صفائی کرنے والا',
  'Gardener': 'مالی',
  'Domestic Helper': 'گھریلو مددگار',
  'Appliance Repair Technician': 'گھریلو آلات کا مستری',
  'Solar Technician': 'سولر ٹیکنیشن',
  'Pest Control Technician': 'کیڑوں کا خاتمہ کرنے والا',
  'Other Local Service': 'دیگر مقامی خدمت',
  'General Labourer': 'عام مزدور',
  'Construction Helper': 'تعمیراتی مددگار',
  'Material Handling': 'سامان کی نقل و حرکت',
  'Site Cleaning': 'کام کی جگہ کی صفائی',
  'Brickwork': 'اینٹوں کا کام',
  'Plastering': 'پلستر',
  'Concrete Work': 'کنکریٹ کا کام',
  'Boundary Walls': 'چار دیواری',
  'Wiring Repair': 'وائرنگ کی مرمت',
  'Wiring Installation': 'وائرنگ لگانا',
  'Fault Finding': 'خرابی کی تلاش',
  'Switchboard Installation': 'سوئچ بورڈ لگانا',
  'Solar Wiring': 'سولر وائرنگ',
  'Leakage Repair': 'رساؤ کی مرمت',
  'Pipe Installation': 'پائپ لگانا',
  'Bathroom Installation': 'باتھ روم کا کام',
  'Kitchen Plumbing': 'باورچی خانے کی پلمبنگ',
  'Drain Cleaning': 'نالے کی صفائی',
  'Interior Painting': 'اندرونی پینٹ',
  'Exterior Painting': 'بیرونی پینٹ',
  'Surface Preparation': 'سطح کی تیاری',
  'Spray Painting': 'اسپرے پینٹ',
  'Wall Finishing': 'دیوار کی فنشنگ',
  'Furniture Repair': 'فرنیچر کی مرمت',
  'Doors and Windows': 'دروازے اور کھڑکیاں',
  'Kitchen Cabinets': 'باورچی خانے کی الماریاں',
  'Custom Furniture': 'آرڈر پر فرنیچر',
  'Gate Fabrication': 'گیٹ بنانا',
  'Grills and Railings': 'گرِل اور ریلنگ',
  'Metal Repair': 'دھات کی مرمت',
  'Steel Structures': 'اسٹیل کا ڈھانچہ',
  'Floor Tiles': 'فرش کی ٹائلیں',
  'Wall Tiles': 'دیوار کی ٹائلیں',
  'Bathroom Tiling': 'باتھ روم کی ٹائلیں',
  'Tile Repair': 'ٹائل کی مرمت',
  'AC Installation': 'اے سی لگانا',
  'AC Repair': 'اے سی کی مرمت',
  'AC Servicing': 'اے سی کی سروس',
  'Refrigerator Repair': 'فریج کی مرمت',
  'House Cleaning': 'گھر کی صفائی',
  'Deep Cleaning': 'مکمل صفائی',
  'Office Cleaning': 'دفتر کی صفائی',
  'Water Tank Cleaning': 'پانی کی ٹینکی کی صفائی',
  'Garden Maintenance': 'باغ کی دیکھ بھال',
  'Lawn Care': 'لان کی دیکھ بھال',
  'Planting': 'پودے لگانا',
  'Tree Pruning': 'درختوں کی کٹائی',
  'Washing Machine Repair': 'واشنگ مشین کی مرمت',
  'Oven Repair': 'اوون کی مرمت',
  'Water Pump Repair': 'پانی کی موٹر کی مرمت',
  'Small Appliance Repair': 'چھوٹے آلات کی مرمت',
  'Household Help': 'گھر کے کام میں مدد',
  'Cooking': 'کھانا پکانا',
  'Laundry': 'کپڑے دھونا',
  'Part Time Help': 'جز وقتی مدد',
  'Construction role': 'تعمیراتی کردار',
  'Types of work': 'کام کی اقسام',
  'Can join a team': 'ٹیم میں شامل ہو سکتے ہیں',
  'Labourer': 'مزدور',
  'Helper': 'مددگار',
  'Team leader': 'ٹیم کا سربراہ',
  'Material handling': 'سامان اٹھانا',
  'Digging': 'کھدائی',
  'Concrete mixing': 'کنکریٹ ملانا',
  'Site cleaning': 'جگہ کی صفائی',
  'Masonry specializations': 'مستری کی مہارتیں',
  'Concrete work': 'کنکریٹ کا کام',
  'Boundary walls': 'چار دیواری',
  'Can bring helpers': 'مددگار ساتھ لا سکتے ہیں',
  'Work settings': 'کام کی جگہیں',
  'Residential': 'رہائشی',
  'Commercial': 'تجارتی',
  'Industrial': 'صنعتی',
  'Electrical capabilities': 'بجلی کے کام کی مہارتیں',
  'Wiring': 'وائرنگ',
  'Installation': 'تنصیب',
  'Troubleshooting': 'خرابی دور کرنا',
  'Switchboards': 'سوئچ بورڈ',
  'Solar wiring': 'سولر وائرنگ',
  'Relevant qualifications (optional)': 'متعلقہ اسناد (اختیاری)',
  'Plumbing services': 'پلمبنگ کی خدمات',
  'Pipe installation': 'پائپ لگانا',
  'Leakage repair': 'رساؤ کی مرمت',
  'Bathroom installation': 'باتھ روم کا کام',
  'Kitchen installation': 'باورچی خانے کا کام',
  'Drain cleaning': 'نالے کی صفائی',
  'Offers emergency appointments': 'ہنگامی کام کے لیے دستیاب',
  'Painting work': 'پینٹ کا کام',
  'Interior': 'اندرونی',
  'Exterior': 'بیرونی',
  'Both': 'دونوں',
  'Specializations': 'خصوصی مہارتیں',
  'Surface preparation': 'سطح کی تیاری',
  'Spray painting': 'اسپرے پینٹ',
  'Texture finishing': 'ٹیکسچر فنشنگ',
  'Wood finishing': 'لکڑی کی فنشنگ',
  'Materials worked with': 'استعمال کیے جانے والے مواد',
  'Solid wood': 'ٹھوس لکڑی',
  'Plywood': 'پلائی ووڈ',
  'MDF': 'ایم ڈی ایف',
  'Laminates': 'لیمینیٹ',
  'Welding methods': 'ویلڈنگ کے طریقے',
  'Arc welding': 'آرک ویلڈنگ',
  'MIG': 'مِگ',
  'TIG': 'ٹِگ',
  'Gas welding': 'گیس ویلڈنگ',
  'Tile materials': 'ٹائل کے مواد',
  'Ceramic': 'سیرامک',
  'Porcelain': 'پورسلین',
  'Marble': 'سنگ مرمر',
  'Granite': 'گرینائٹ',
  'Technician services': 'ٹیکنیشن کی خدمات',
  'Repair': 'مرمت',
  'Maintenance': 'دیکھ بھال',
  'Supported equipment': 'وہ آلات جن پر کام کرتے ہیں',
  'Split AC': 'اسپلٹ اے سی',
  'Window AC': 'ونڈو اے سی',
  'Inverter AC': 'انورٹر اے سی',
  'Refrigerator': 'فریج',
  'Freezer': 'فریزر',
  'Brings cleaning supplies': 'صفائی کا سامان ساتھ لاتے ہیں',
  'Cleaning settings': 'صفائی کی جگہیں',
  'Homes': 'گھر',
  'Offices': 'دفاتر',
  'Shops': 'دکانیں',
  'Water tanks': 'پانی کی ٹینکیاں',
  'Brings gardening tools': 'باغبانی کے اوزار ساتھ لاتے ہیں',
  'Supported appliances': 'وہ آلات جن کی مرمت کرتے ہیں',
  'Washing machines': 'واشنگ مشینیں',
  'Ovens': 'اوون',
  'Water pumps': 'پانی کی موٹریں',
  'Small appliances': 'چھوٹے آلات',
  'Household tasks offered': 'گھر کے وہ کام جو کرتے ہیں',
  'Household cleaning': 'گھر کی صفائی',
  'Ironing': 'استری',
  'Preferred work arrangement': 'کام کا پسندیدہ طریقہ',
  'Part time': 'جز وقتی',
  'Full time': 'کل وقتی',
  'Occasional': 'کبھی کبھار',
  'Systems supported': 'وہ سسٹم جن پر کام کرتے ہیں',
  'On grid': 'آن گرڈ',
  'Off grid': 'آف گرڈ',
  'Hybrid': 'ہائبرڈ',
  'Treatments offered': 'دستیاب طریقے',
  'Termites': 'دیمک',
  'Cockroaches': 'کاکروچ',
  'General pests': 'عام کیڑے',
  'Relevant training (optional)': 'متعلقہ تربیت (اختیاری)',
  'Levels taught': 'پڑھائی کی سطح',
  'Primary': 'پرائمری',
  'Middle': 'مڈل',
  'Secondary': 'سیکنڈری',
  'College': 'کالج',
  'Adult learning': 'بالغوں کی تعلیم',
  'Service setting': 'خدمت کی جگہ',
  'At customer location': 'گاہک کی جگہ',
  'At salon': 'سیلون میں',
  'Describe your service': 'اپنی خدمت کی تفصیل بتائیں',
};
