const Map<String, String> urduStrings = {
  'Connecting to Khidmat…': 'خدمت سے رابطہ ہو رہا ہے…',
  'Unable to connect': 'رابطہ نہیں ہو سکا',
  'Khidmat services are not ready yet. The app owner needs to finish service setup. Please try again later.':
      'خدمت کی سہولتیں ابھی تیار نہیں۔ ایپ کے مالک کو تنصیب مکمل کرنا ہوگی۔ کچھ دیر بعد دوبارہ کوشش کریں۔',
  'Could not connect to Khidmat. Check your connection and try again.':
      'خدمت سے رابطہ نہیں ہوا۔ اپنا انٹرنیٹ چیک کر کے دوبارہ کوشش کریں۔',
  'Sign in is temporarily unavailable. Please try again.':
      'لاگ اِن کی سہولت عارضی طور پر دستیاب نہیں۔ دوبارہ کوشش کریں۔',
  'The connection took too long. Please try again.':
      'رابطے میں زیادہ وقت لگ رہا ہے۔ دوبارہ کوشش کریں۔',
  'Phone sign in is not available yet. Please use email.':
      'فون سے لاگ اِن ابھی دستیاب نہیں۔ براہِ کرم ای میل استعمال کریں۔',
  'Could not save or load this information. Please try again.':
      'معلومات محفوظ یا لوڈ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔',
  'Could not upload or load the photo. Please try again.':
      'تصویر اپ لوڈ یا لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
  'Forgot password?': 'پاس ورڈ بھول گئے؟',
  'Enter your password': 'اپنا پاس ورڈ لکھیں',
  'Show password': 'پاس ورڈ دکھائیں',
  'Hide password': 'پاس ورڈ چھپائیں',
  'Choose a new password': 'نیا پاس ورڈ منتخب کریں',
  'Confirm password': 'پاس ورڈ دوبارہ لکھیں',
  'Passwords do not match': 'دونوں پاس ورڈ ایک جیسے نہیں',
  'Save password': 'پاس ورڈ محفوظ کریں',
  'Password updated.': 'پاس ورڈ تبدیل ہو گیا۔',
  'If an account exists, a password reset link has been sent. Check your email.':
      'اگر اکاؤنٹ موجود ہے تو پاس ورڈ تبدیل کرنے کا لنک بھیج دیا گیا ہے۔ اپنی ای میل چیک کریں۔',
  'No times available on this date. Choose another day.':
      'اس تاریخ کو کوئی وقت دستیاب نہیں۔ دوسرا دن منتخب کریں۔',
  'Refresh available times': 'دستیاب اوقات دوبارہ دیکھیں',
  "Connect Khidmat": "خدمت سے رابطہ",
  "Welcome to Khidmat": "خدمت میں خوش آمدید",
  "Supabase project URL": "Supabase پروجیکٹ کا پتہ",
  "Publishable or anon key": "پبلک ایپ کی",
  "Connecting…": "رابطہ ہو رہا ہے…",
  "Connect": "رابطہ کریں",
  "Use a publishable key, never a secret key.":
      "پبلک ایپ کی استعمال کریں، خفیہ کی ہرگز نہیں۔",
  "Trusted help, in your language.": "قابلِ اعتماد مدد، آپ کی زبان میں۔",
  "Sign in": "لاگ اِن",
  "Create your account": "اپنا اکاؤنٹ بنائیں",
  "Create account": "اکاؤنٹ بنائیں",
  "Your name": "آپ کا نام",
  "Email": "ای میل",
  "Password": "پاس ورڈ",
  "Enter your name": "اپنا نام لکھیں",
  "Enter a valid email": "درست ای میل لکھیں",
  "Use at least 8 characters": "کم از کم ۸ حروف استعمال کریں",
  "Please wait…": "براہِ کرم انتظار کریں…",
  "Already registered? Sign in": "اکاؤنٹ موجود ہے؟ لاگ اِن کریں",
  "New here? Create an account": "نئے صارف ہیں؟ اکاؤنٹ بنائیں",
  "Continue with phone": "فون نمبر سے لاگ اِن",
  "Continue with email": "ای میل سے لاگ اِن",
  "Check your email to confirm your account, then sign in.":
      "اپنی ای میل سے اکاؤنٹ کی تصدیق کریں، پھر لاگ اِن کریں۔",
  "Phone sign in": "فون سے لاگ اِن",
  "Phone number": "فون نمبر",
  "Enter your phone number. We will send you a verification code.":
      "اپنا فون نمبر لکھیں۔ آپ کو تصدیقی کوڈ بھیجا جائے گا۔",
  "SMS code": "ایس ایم ایس کوڈ",
  "Send code": "کوڈ بھیجیں",
  "Verify & continue": "تصدیق کر کے آگے بڑھیں",
  "Resend code": "دوبارہ کوڈ بھیجیں",
  "Use another number": "دوسرا نمبر استعمال کریں",
  "Enter the six-digit SMS code.": "ایس ایم ایس کا چھ ہندسوں والا کوڈ لکھیں۔",
  "Code sent to {phone}": "کوڈ {phone} پر بھیجا گیا ہے",
  "Resend in {seconds}s": "{seconds} سیکنڈ بعد دوبارہ بھیجیں",
  "Complete your profile": "اپنی پروفائل مکمل کریں",
  "How will you use Khidmat?": "آپ خدمت کیسے استعمال کریں گے؟",
  "Worker": "کام کرنے والا",
  "Work giver": "کام دینے والا",
  "I offer services and receive jobs.":
      "میں خدمات پیش کرتا ہوں اور کام حاصل کرتا ہوں۔",
  "I need help and want to hire workers.":
      "مجھے مدد چاہیے اور میں کاریگر کی خدمات لینا چاہتا ہوں۔",
  "Choose your role": "اپنا کردار منتخب کریں",
  "Profession": "پیشہ",
  "Working experience (years)": "کام کا تجربہ (سال)",
  "About you / work details": "اپنے بارے میں / کام کی تفصیل",
  "Tell customers about your skills and experience.":
      "صارفین کو اپنی مہارت اور تجربے کے بارے میں بتائیں۔",
  "Describe the kind of help you usually need.":
      "بتائیں کہ آپ کو عموماً کس کام میں مدد چاہیے۔",
  "Continue to dashboard": "ڈیش بورڈ پر جائیں",
  "Enter your profession": "اپنا پیشہ لکھیں",
  "Enter experience from 0 to 60 years": "۰ سے ۶۰ سال تک تجربہ لکھیں",
  "Add a short description": "مختصر تفصیل لکھیں",
  "Your profile could not be loaded.": "آپ کی پروفائل لوڈ نہیں ہو سکی۔",
  "Worker dashboard": "کاریگر کا ڈیش بورڈ",
  "Work giver dashboard": "کام دینے والے کا ڈیش بورڈ",
  "Welcome, {name}": "خوش آمدید، {name}",
  "Manage your listing and incoming work.":
      "اپنی خدمات اور آنے والے کام سنبھالیں۔",
  "Your worker profile": "آپ کی کاریگر پروفائل",
  "My jobs": "میرے کام",
  "Requests, accepted jobs and conversations.":
      "درخواستیں، منظور شدہ کام اور گفتگو۔",
  "Edit service listing": "خدمات کی تفصیل بدلیں",
  "Profile details": "پروفائل کی تفصیلات",
  "Edit profile": "پروفائل میں تبدیلی",
  "Account type": "اکاؤنٹ کی قسم",
  "My account": "میرا اکاؤنٹ",
  "Upload profile photo": "پروفائل تصویر اپ لوڈ کریں",
  "City": "شہر",
  "Enter your city": "اپنا شہر لکھیں",
  "Default service address": "کام کے لیے عمومی پتہ",
  "Save profile": "پروفائل محفوظ کریں",
  "Saving…": "محفوظ ہو رہا ہے…",
  "Profile saved.": "پروفائل محفوظ ہو گئی۔",
  "Sign out": "لاگ آؤٹ",
  "Assalamu Alaikum, {name}": "السلام علیکم، {name}",
  "What can we help with?": "آپ کو کس کام میں مدد چاہیے؟",
  "Describe your request in English, Urdu or Roman Urdu.":
      "اپنی ضرورت انگریزی، اردو یا رومن اردو میں لکھیں۔",
  "Your city": "آپ کا شہر",
  "What service do you need?": "آپ کو کون سی خدمت چاہیے؟",
  "Plumber chahiye, pipe leak ho raha hai":
      "پلمبر چاہیے، پائپ سے پانی رس رہا ہے",
  "Find available providers": "دستیاب کاریگر تلاش کریں",
  "Quick services": "فوری خدمات",
  "Offer your services": "اپنی خدمات پیش کریں",
  "Create a listing and manage real bookings.":
      "اپنی خدمات درج کریں اور بکنگ سنبھالیں۔",
  "My bookings and jobs": "میری بکنگ اور کام",
  "Status updates and conversations.": "کام کی صورتِ حال اور گفتگو۔",
  "Enter your city and the service you need.":
      "اپنا شہر اور مطلوبہ خدمت لکھیں۔",
  "AC Technician": "اے سی ٹیکنیشن",
  "Plumber": "پلمبر",
  "Electrician": "الیکٹریشن",
  "Tutor": "ٹیوٹر",
  "Beautician": "بیوٹیشن",
  "Carpenter": "بڑھئی",
  "Painter": "پینٹر",
  "Deep Cleaning": "مکمل صفائی",
  "General Service": "عمومی خدمت",
  "Providers in {city}": "{city} میں کاریگر",
  "Activity log": "سرگرمی کی تفصیل",
  "No approved providers are available for this service in your city yet. Try another service or city.":
      "آپ کے شہر میں اس خدمت کے لیے ابھی کوئی منظور شدہ کاریگر دستیاب نہیں۔ دوسری خدمت یا شہر آزمائیں۔",
  "New provider • No reviews yet": "نیا کاریگر • ابھی کوئی جائزہ نہیں",
  "Booking rate: Rs. {price}": "بکنگ کی قیمت: {price} روپے",
  "Available times: {times}": "دستیاب اوقات: {times}",
  "{years} years of experience": "{years} سال کا تجربہ",
  "{rating} ★ • {reviews} verified reviews • {jobs} completed jobs":
      "{rating} ★ • {reviews} تصدیق شدہ جائزے • {jobs} مکمل کام",
  "View worker profile": "کاریگر کی پروفائل دیکھیں",
  "View quote & book": "قیمت دیکھیں اور بکنگ کریں",
  "Your booking quote": "آپ کی بکنگ کی قیمت",
  "Choose a provider to get a quote.": "قیمت کے لیے کاریگر منتخب کریں۔",
  "Rs. {price}": "{price} روپے",
  "Provider-authorized discount: Rs. {price}":
      "کاریگر کی منظور شدہ رعایت: {price} روپے",
  "Appointment time": "کام کا وقت",
  "{time} (Pakistan time)": "{time} (پاکستانی وقت)",
  "Choose a time": "وقت منتخب کریں",
  "Full service address": "کام کی جگہ کا مکمل پتہ",
  "Enter your full address": "اپنا مکمل پتہ لکھیں",
  "Work details and notes": "کام کی تفصیل اور نوٹس",
  "The provider must accept your request. Payment is cash after completion.":
      "کاریگر کو درخواست منظور کرنا ہوگی۔ ادائیگی کام مکمل ہونے پر نقد ہوگی۔",
  "Reserving…": "وقت محفوظ ہو رہا ہے…",
  "Request booking": "بکنگ کی درخواست",
  "Refresh quote": "نئی قیمت لیں",
  "This rate is authorized by the provider. The quote is valid for 10 minutes. Payment is cash after service. Extra work must be agreed separately.":
      "یہ قیمت کاریگر کی منظور کردہ ہے اور ۱۰ منٹ تک درست ہے۔ ادائیگی کام کے بعد نقد ہوگی۔ اضافی کام پر الگ اتفاق ضروری ہے۔",
  "Provider dashboard": "کاریگر کا ڈیش بورڈ",
  "Listing approved": "خدمات منظور ہو گئیں",
  "Approval pending": "منظوری کا انتظار",
  "Customers can find you when available.":
      "دستیابی کی صورت میں صارفین آپ کو تلاش کر سکتے ہیں۔",
  "The app owner will review your listing before it becomes visible.":
      "آپ کی خدمات ظاہر ہونے سے پہلے ایپ کا منتظم جائزہ لے گا۔",
  "Business or provider name": "کاروبار یا کاریگر کا نام",
  "Service": "خدمت",
  "Service area": "خدمت کا علاقہ",
  "Public business phone (optional)": "کاروباری فون نمبر (اختیاری)",
  "Standard price (Rs.)": "عام قیمت (روپے)",
  "Authorized booking rate (Rs.)": "منظور شدہ بکنگ قیمت (روپے)",
  "Daily times (Pakistan time)": "روزانہ کے اوقات (پاکستانی وقت)",
  "Example: 09:00,12:00,15:00": "مثال: 09:00,12:00,15:00",
  "Available for bookings": "بکنگ کے لیے دستیاب",
  "Save listing": "خدمات محفوظ کریں",
  "Submit listing": "خدمات درج کریں",
  "View booking requests & update jobs":
      "بکنگ کی درخواستیں اور کام کی صورتِ حال دیکھیں",
  "Fill this field": "یہ خانہ پُر کریں",
  "Enter a valid rupee amount": "روپوں میں درست رقم لکھیں",
  "Listing updated.": "خدمات کی تفصیل محفوظ ہو گئی۔",
  "Listing submitted for approval.": "خدمات منظوری کے لیے بھیج دی گئیں۔",
  "The booking rate cannot exceed the standard rate.":
      "بکنگ کی قیمت عام قیمت سے زیادہ نہیں ہو سکتی۔",
  "Use up to 24 times in HH:MM format separated by commas.":
      "HH:MM انداز میں زیادہ سے زیادہ ۲۴ اوقات لکھیں، اور ان کے درمیان کاما لگائیں۔",
  "Set your service details. The booking rate is the price you authorize Khidmat to offer customers. Set both prices equal to disable discounts.":
      "اپنی خدمات کی تفصیل لکھیں۔ بکنگ کی قیمت وہ رقم ہے جو آپ صارفین کے لیے منظور کرتے ہیں۔ رعایت نہ دینے کے لیے دونوں قیمتیں برابر رکھیں۔",
  "Bookings & jobs": "بکنگ اور کام",
  "Refresh": "دوبارہ لوڈ کریں",
  "Your bookings and provider jobs will appear here.":
      "آپ کی بکنگ اور کام یہاں نظر آئیں گے۔",
  "Your job": "آپ کا کام",
  "Booking details": "بکنگ کی تفصیل",
  "Booking not found.": "بکنگ نہیں ملی۔",
  "Waiting for acceptance": "منظوری کا انتظار",
  "Accepted": "منظور شدہ",
  "On the way": "راستے میں",
  "Service in progress": "کام جاری ہے",
  "Completed": "مکمل",
  "Cancelled": "منسوخ",
  "Declined": "مسترد",
  "pending": "منظوری کا انتظار",
  "accepted": "منظور شدہ",
  "on the way": "راستے میں",
  "in progress": "کام جاری ہے",
  "completed": "مکمل",
  "cancelled": "منسوخ",
  "declined": "مسترد",
  "Reference: {id}": "بکنگ نمبر: {id}",
  "Provider: {name}": "کاریگر: {name}",
  "{date} • {time} (Pakistan time)": "{date} • {time} (پاکستانی وقت)",
  "Rs. {price} • Cash after service": "{price} روپے • کام کے بعد نقد ادائیگی",
  "Open conversation": "گفتگو کھولیں",
  "Call provider": "کاریگر کو فون کریں",
  "Could not open the dialer.": "فون کرنے کی سہولت نہیں کھل سکی۔",
  "Accept job": "کام منظور کریں",
  "Decline": "مسترد کریں",
  "Mark on the way": "راستے میں ہونے کی اطلاع دیں",
  "Start service": "کام شروع کریں",
  "Mark completed": "کام مکمل کریں",
  "Cancel booking": "بکنگ منسوخ کریں",
  "Leave a verified review": "تصدیق شدہ جائزہ لکھیں",
  "Activity": "سرگرمی",
  "Cancel booking?": "بکنگ منسوخ کریں؟",
  "Decline this job?": "یہ کام مسترد کریں؟",
  "The other person will see this change immediately.":
      "دوسرے شخص کو یہ تبدیلی فوراً نظر آئے گی۔",
  "Keep booking": "بکنگ برقرار رکھیں",
  "Confirm": "تصدیق کریں",
  "Rate this service": "خدمت کی درجہ بندی",
  "{stars} stars": "{stars} ستارے",
  "Your feedback": "آپ کی رائے",
  "Close": "بند کریں",
  "Submit": "جمع کریں",
  "Thank you for your review.": "آپ کے جائزے کا شکریہ۔",
  "Booking conversation": "بکنگ کی گفتگو",
  "Say hello or share a photo of the work.":
      "سلام کریں یا کام کی تصویر بھیجیں۔",
  "You": "آپ",
  "Booking participant": "گفتگو کا ساتھی",
  "Share photo": "تصویر بھیجیں",
  "Message…": "پیغام…",
  "Send": "بھیجیں",
  "Try again": "دوبارہ کوشش کریں",
  "Return home": "مرکزی صفحے پر جائیں",
  "Finish the Supabase database setup before using this feature.":
      "اس سہولت کے لیے پہلے Supabase ڈیٹابیس کی تنصیب مکمل کریں۔",
  "You do not have permission for this action.":
      "آپ کو اس عمل کی اجازت نہیں ہے۔",
  "This record already exists.": "یہ ریکارڈ پہلے سے موجود ہے۔",
  "Could not complete the request. Check your connection and try again.":
      "درخواست مکمل نہیں ہو سکی۔ اپنا رابطہ چیک کر کے دوبارہ کوشش کریں۔",
  "Choose an image smaller than 5 MB.": "۵ ایم بی سے چھوٹی تصویر منتخب کریں۔",
  "Choose a JPEG, PNG or WebP image.": "JPEG، PNG یا WebP تصویر منتخب کریں۔",
  "Phone logins are disabled": "فون سے لاگ اِن کی سہولت بند ہے",
  "Invalid login credentials": "ای میل یا پاس ورڈ درست نہیں",
  "Email not confirmed": "ای میل کی تصدیق نہیں ہوئی",
  "Using Khidmat": "خدمت کا استعمال",
  "Find a provider": "کاریگر تلاش کریں",
  "Book a service": "خدمت بک کریں",
  "Updates and chat": "تازہ صورتِ حال اور گفتگو",
  "Payment": "ادائیگی",
  "Reviews": "جائزے",
  "Enter your city and describe the work. Only approved, available listings appear.":
      "اپنا شہر اور کام کی تفصیل لکھیں۔ صرف منظور شدہ اور دستیاب کاریگر دکھائے جاتے ہیں۔",
  "Review the provider-authorized quote, choose a date and time, and enter your full address. The request stays pending until the provider accepts it.":
      "کاریگر کی منظور کردہ قیمت دیکھیں، تاریخ اور وقت چنیں اور مکمل پتہ لکھیں۔ کاریگر کی منظوری تک درخواست زیرِ انتظار رہتی ہے۔",
  "Open My bookings to see current status and chat with the other participant. You can share photos of the work.":
      "میری بکنگ کھول کر تازہ صورتِ حال دیکھیں اور دوسرے شخص سے گفتگو کریں۔ کام کی تصاویر بھی بھیج سکتے ہیں۔",
  "Pay cash after service. Additional work or materials must be agreed with the provider.":
      "کام کے بعد نقد ادائیگی کریں۔ اضافی کام یا سامان پر کاریگر سے الگ اتفاق کریں۔",
  "Create a listing in the provider dashboard. The app owner reviews it before publication. Set your authorized prices and available daily times.":
      "کاریگر کے ڈیش بورڈ میں خدمات درج کریں۔ منتظم اشاعت سے پہلے جائزہ لیتا ہے۔ اپنی قیمتیں اور روزانہ کے دستیاب اوقات لکھیں۔",
  "A customer can review each completed booking once. New providers have no review history.":
      "صارف ہر مکمل بکنگ پر ایک جائزہ لکھ سکتا ہے۔ نئے کاریگر کے سابقہ جائزے نہیں ہوتے۔",
  "Continue": "آگے بڑھیں",
  "Or use email": "یا ای میل استعمال کریں",
  "Worker profile": "کاریگر کی پروفائل",
  "Set your rates and availability.": "اپنی قیمتیں اور دستیاب اوقات لکھیں۔",
  "Edit your profile or change your account type.":
      "اپنی پروفائل یا اکاؤنٹ کی قسم بدلیں۔",
  "Edit profile and account type": "پروفائل اور اکاؤنٹ کی قسم بدلیں",
  "Waiting for provider": "کاریگر کی منظوری کا انتظار",
  "Provider on the way": "کاریگر راستے میں ہے",
  "{date} at {time} • Rs. {price}": "{date}، {time} بجے • {price} روپے",
  "Use a phone number with country code, such as +923001234567.":
      "ملکی کوڈ کے ساتھ فون نمبر لکھیں، مثلاً +923001234567۔",
  "Quote not found": "قیمت کی درخواست نہیں ملی",
  "Quote expired; request a new price": "قیمت کی مدت ختم ہو گئی؛ نئی قیمت لیں",
  "Provider is unavailable": "کاریگر دستیاب نہیں",
  "You cannot book yourself": "آپ خود اپنی بکنگ نہیں کر سکتے",
  "No available slots": "کوئی وقت دستیاب نہیں",
  "Choose a date within the next 90 days": "اگلے ۹۰ دنوں میں کوئی تاریخ چنیں",
  "Choose an available time slot": "دستیاب وقت منتخب کریں",
  "That appointment time has already passed": "یہ وقت گزر چکا ہے",
  "Enter a full service address": "کام کی جگہ کا مکمل پتہ لکھیں",
  "This time slot was just booked; choose another slot":
      "یہ وقت ابھی بک ہو گیا ہے؛ دوسرا وقت چنیں",
  "Booking not found": "بکنگ نہیں ملی",
  "This status change is not allowed": "یہ تبدیلی کرنے کی اجازت نہیں",
  "Complete your worker details": "کاریگر کی پروفائل مکمل کریں",
  "Profile not found": "پروفائل نہیں ملی",
  "Sign in first": "پہلے لاگ اِن کریں",
  "No activity yet": "ابھی کوئی سرگرمی نہیں",
  "Start a service request to see activity.":
      "سرگرمی دیکھنے کے لیے خدمت کی درخواست شروع کریں۔",
  "Service: {service}": "خدمت: {service}",
  "City selected by customer: {city}": "صارف کا منتخب شہر: {city}",
  "Local language matching": "مقامی زبان میں درخواست کی پہچان",
  "Queried approved, available listings in {city}":
      "{city} میں منظور شدہ اور دستیاب کاریگر تلاش کیے",
  "{count} matching providers": "{count} متعلقہ کاریگر",
  "Ranked by verified reviews and completed jobs":
      "تصدیق شدہ جائزوں اور مکمل کاموں سے ترتیب دی",
  "New providers display without an invented reputation":
      "نئے کاریگر کو حقیقی سابقہ ریکارڈ کے ساتھ دکھایا جاتا ہے",
  "Server quote: {id}": "سرور کی قیمت کا نمبر: {id}",
  "Provider-authorized rate: Rs. {price}":
      "کاریگر کی منظور شدہ قیمت: {price} روپے",
  "Booking {id} persisted": "بکنگ {id} محفوظ ہو گئی",
  "Time slot reserved; waiting for provider acceptance":
      "وقت محفوظ ہو گیا؛ کاریگر کی منظوری کا انتظار",
  "Address is too long": "پتہ بہت طویل ہے",
  "Profession is too long": "پیشے کی تفصیل بہت طویل ہے",
  "Description is too long": "تفصیل بہت طویل ہے",
  "This build needs its Supabase project connection. Enter the project URL and public app key supplied by the app owner.":
      "اس ایپ کو Supabase پروجیکٹ سے جوڑیں۔ ایپ کے مالک کا دیا ہوا پروجیکٹ کا پتہ اور پبلک کی لکھیں۔",
  "Never enter a service-role key, secret key or database password.":
      "خفیہ کی یا ڈیٹابیس کا پاس ورڈ کبھی درج نہ کریں۔",
};
