const Map<String, String> urduStrings = {
  'Your records are full. Save a backup before removing old records.':
      'آپ کے ریکارڈ کی جگہ بھر گئی ہے۔ پرانے ریکارڈ ہٹانے سے پہلے بیک اپ محفوظ کریں۔',
  'Invalid contact': 'رابطہ درست نہیں',
  'Invalid job': 'کام کا ریکارڈ درست نہیں',
  'Khidmat': 'خدمت',
  'Home': 'ہوم',
  'Workers': 'کاریگر',
  'Jobs': 'کام',
  'Profile': 'پروفائل',
  'Trusted local help, in your language.':
      'آپ کی زبان میں قابلِ اعتماد مقامی مدد۔',
  'Keep worker contacts, plan service appointments and manage your jobs.':
      'کاریگروں کے رابطے محفوظ کریں، ملاقات طے کریں اور اپنے کام سنبھالیں۔',
  'Your records stay on this phone. Call, send SMS or share a request to agree on work.':
      'آپ کی معلومات اسی فون میں رہتی ہیں۔ کام طے کرنے کے لیے کال کریں، ایس ایم ایس بھیجیں یا درخواست شیئر کریں۔',
  'Get started': 'شروع کریں',
  'Restore backup': 'بیک اپ بحال کریں',
  'How Khidmat works': 'خدمت کیسے کام کرتی ہے',
  'Create your profile': 'اپنی پروفائل بنائیں',
  'Edit profile': 'پروفائل تبدیل کریں',
  'Save profile': 'پروفائل محفوظ کریں',
  'How will you use Khidmat?': 'آپ خدمت کیسے استعمال کریں گے؟',
  'Worker': 'کاریگر',
  'Work giver': 'کام دینے والا',
  'Your name': 'آپ کا نام',
  'City': 'شہر',
  'Phone number': 'فون نمبر',
  'Phone number (optional)': 'فون نمبر (اختیاری)',
  'Profession': 'پیشہ',
  'Working experience (years)': 'کام کا تجربہ (سال)',
  'About you / work details': 'آپ کے بارے میں / کام کی تفصیل',
  'This profile is saved on this phone. Share your details directly with people you want to work with.':
      'یہ پروفائل اسی فون میں محفوظ ہے۔ جن لوگوں کے ساتھ کام کرنا چاہتے ہیں، انہیں اپنی تفصیلات براہِ راست بھیجیں۔',
  'Profile saved on your phone.': 'پروفائل آپ کے فون میں محفوظ ہو گئی۔',
  'Saving…': 'محفوظ ہو رہا ہے…',
  'Worker dashboard': 'کاریگر کا ڈیش بورڈ',
  'Work giver dashboard': 'کام دینے والے کا ڈیش بورڈ',
  'Your work, organized.': 'آپ کے کام، ترتیب سے۔',
  'Good help starts with good contacts.':
      'اچھی مدد، اچھے رابطوں سے شروع ہوتی ہے۔',
  'Add job': 'کام شامل کریں',
  'Plan a service': 'خدمت کی ملاقات طے کریں',
  'Active jobs': 'جاری کام',
  'Completed': 'مکمل',
  'Saved workers': 'محفوظ کاریگر',
  'Next appointments': 'اگلی ملاقاتیں',
  'A clear day ahead': 'ابھی کوئی ملاقات نہیں',
  'Add an appointment to keep track of your work.':
      'اپنے کام کا حساب رکھنے کے لیے ملاقات شامل کریں۔',
  'View all jobs': 'تمام کام دیکھیں',
  'People you can call for local services.':
      'مقامی کام کے لیے ان لوگوں کو کال کریں۔',
  'Share my profile': 'میری پروفائل شیئر کریں',
  'Send your profession and contact details.':
      'اپنا پیشہ اور رابطے کی تفصیلات بھیجیں۔',
  'Saved on this phone': 'اسی فون میں محفوظ',
  '{count} years of experience': '{count} سال کا تجربہ',
  'Add workers you know. This list is saved on your phone.':
      'اپنے جاننے والے کاریگر شامل کریں۔ یہ فہرست آپ کے فون میں محفوظ ہے۔',
  'Search name, city or service': 'نام، شہر یا خدمت تلاش کریں',
  'Favorites': 'پسندیدہ',
  'Favorite': 'پسندیدہ',
  'All': 'تمام',
  'No worker contacts yet': 'ابھی کوئی کاریگر محفوظ نہیں',
  'No matching contacts': 'کوئی متعلقہ رابطہ نہیں ملا',
  'Save a real worker contact to call them, send requests and plan jobs.':
      'کاریگر کا حقیقی رابطہ محفوظ کریں تاکہ کال، درخواست اور ملاقات طے کر سکیں۔',
  'Try another name, city or service.': 'دوسرا نام، شہر یا خدمت تلاش کریں۔',
  'Add worker': 'کاریگر شامل کریں',
  'Edit worker': 'کاریگر تبدیل کریں',
  'Worker name': 'کاریگر کا نام',
  'Service': 'خدمت',
  'Plumber': 'پلمبر',
  'Electrician': 'الیکٹریشن',
  'AC Technician': 'اے سی ٹیکنیشن',
  'Carpenter': 'بڑھئی',
  'Painter': 'پینٹر',
  'Cleaning': 'صفائی',
  'Tutor': 'ٹیوٹر',
  'Beautician': 'بیوٹیشن',
  'Other': 'دیگر',
  'Starting rate (Rs.)': 'ابتدائی قیمت (روپے)',
  'Starting rate': 'ابتدائی قیمت',
  'Use 0 when the price needs to be agreed.':
      'اگر قیمت بعد میں طے کرنی ہے تو ۰ لکھیں۔',
  'Work details / notes': 'کام کی تفصیل / نوٹس',
  'Favorite contact': 'پسندیدہ رابطہ',
  'Save worker': 'کاریگر محفوظ کریں',
  'Worker contact saved.': 'کاریگر کا رابطہ محفوظ ہو گیا۔',
  'Contact not found': 'رابطہ نہیں ملا',
  'This worker contact was removed.': 'یہ کاریگر کا رابطہ حذف ہو گیا ہے۔',
  'Worker details': 'کاریگر کی تفصیلات',
  'Price to be agreed': 'قیمت طے کرنا باقی ہے',
  'Rs. {amount}': '{amount} روپے',
  'Call': 'کال کریں',
  'Send SMS': 'ایس ایم ایس بھیجیں',
  'Share worker': 'کاریگر کی تفصیل شیئر کریں',
  'Plan an appointment': 'ملاقات طے کریں',
  'Hello, I would like to ask about your services.':
      'السلام علیکم، میں آپ کی خدمات کے بارے میں پوچھنا چاہتا ہوں۔',
  'Remove from favorites': 'پسندیدہ سے نکالیں',
  'Add to favorites': 'پسندیدہ میں شامل کریں',
  'Confirm the worker’s availability and final price directly before the appointment.':
      'ملاقات سے پہلے کاریگر کی دستیابی اور آخری قیمت براہِ راست طے کریں۔',
  'Delete contact': 'رابطہ حذف کریں',
  'Delete contact?': 'رابطہ حذف کریں؟',
  'The contact will be removed. Your existing job records will stay.':
      'رابطہ حذف ہو جائے گا۔ پہلے سے محفوظ کام کی تفصیلات باقی رہیں گی۔',
  'My jobs': 'میرے کام',
  'Active': 'جاری',
  'Cancelled': 'منسوخ',
  'Planned': 'منصوبہ بنایا',
  'Confirmed': 'طے شدہ',
  'In progress': 'کام جاری ہے',
  'Confirm dates and prices directly with the other person.':
      'تاریخ اور قیمت دوسرے شخص کے ساتھ براہِ راست طے کریں۔',
  'No jobs here yet': 'یہاں ابھی کوئی کام نہیں',
  'Save an appointment to keep the date, address, price and progress together.':
      'تاریخ، پتہ، قیمت اور کام کی پیش رفت ایک جگہ رکھنے کے لیے ملاقات محفوظ کریں۔',
  'Edit job': 'کام تبدیل کریں',
  'Saved worker': 'محفوظ کاریگر',
  'Enter details': 'تفصیلات لکھیں',
  'Client name': 'گاہک کا نام',
  'This saves an appointment on your phone. Contact the other person to agree on it.':
      'یہ ملاقات آپ کے فون میں محفوظ ہوگی۔ اسے طے کرنے کے لیے دوسرے شخص سے رابطہ کریں۔',
  'Work address': 'کام کا پتہ',
  'Agreed amount (Rs.)': 'طے شدہ رقم (روپے)',
  'Job notes': 'کام کے نوٹس',
  'Save job': 'کام محفوظ کریں',
  'Job saved on your phone.': 'کام آپ کے فون میں محفوظ ہو گیا۔',
  'Job not found': 'کام نہیں ملا',
  'This job record was removed.': 'یہ کام کی تفصیل حذف ہو گئی ہے۔',
  'Job details': 'کام کی تفصیلات',
  'No phone number saved': 'فون نمبر محفوظ نہیں',
  'Record status': 'کام کی حالت',
  'Update this record after agreeing with the other person.':
      'دوسرے شخص کے ساتھ بات طے کرنے کے بعد یہ ریکارڈ تبدیل کریں۔',
  'Job status saved.': 'کام کی حالت محفوظ ہو گئی۔',
  'Share request': 'درخواست شیئر کریں',
  'Delete job': 'کام حذف کریں',
  'Delete job?': 'کام حذف کریں؟',
  'This removes the job record from this phone.':
      'اس فون سے یہ کام کی تفصیل حذف ہو جائے گی۔',
  'Khidmat appointment request': 'خدمت کی ملاقات کی درخواست',
  'Date': 'تاریخ',
  'Address': 'پتہ',
  'Amount': 'رقم',
  'Please confirm the time and price with me.':
      'براہِ کرم وقت اور قیمت میرے ساتھ طے کریں۔',
  'My profile': 'میری پروفائل',
  'Edit profile and account type': 'پروفائل اور اکاؤنٹ کی قسم بدلیں',
  'Backup and restore': 'بیک اپ اور بحالی',
  'Save backup': 'بیک اپ محفوظ کریں',
  'Restore backup?': 'بیک اپ بحال کریں؟',
  'Restore': 'بحال کریں',
  'Cancel': 'منسوخ کریں',
  'Delete': 'حذف کریں',
  'Backup restored.': 'بیک اپ بحال ہو گیا۔',
  'Save a backup to keep your profile, worker contacts and job records when changing phones.':
      'فون بدلتے وقت پروفائل، کاریگروں کے رابطے اور کام کے ریکارڈ بچانے کے لیے بیک اپ محفوظ کریں۔',
  'Choose a place to save khidmat-backup.json. You can restore that file on another phone.':
      'khidmat-backup.json محفوظ کرنے کی جگہ چنیں۔ آپ یہ فائل دوسرے فون پر بحال کر سکتے ہیں۔',
  'Uninstalling Khidmat or clearing app storage removes your phone records. Save a backup first.':
      'خدمت حذف کرنے یا ایپ کی اسٹوریج صاف کرنے سے فون کے ریکارڈ ختم ہو جاتے ہیں۔ پہلے بیک اپ محفوظ کریں۔',
  'Replace this phone’s profile, workers and jobs with {workers} workers and {jobs} jobs from this backup?':
      'اس فون کی پروفائل، کاریگر اور کام کے ریکارڈ کو اس بیک اپ کے {workers} کاریگروں اور {jobs} کاموں سے بدلیں؟',
  'This backup is too large': 'یہ بیک اپ بہت بڑا ہے',
  'Choose a Khidmat backup file': 'خدمت کی بیک اپ فائل چنیں',
  'Choose a valid Khidmat backup file': 'خدمت کی درست بیک اپ فائل چنیں',
  'This backup contains invalid records': 'اس بیک اپ میں غلط ریکارڈ ہیں',
  'Sharing is unavailable. Please try again.':
      'شیئرنگ دستیاب نہیں۔ دوبارہ کوشش کریں۔',
  'The backup could not be shared. Please try again.':
      'بیک اپ شیئر نہیں ہوا۔ دوبارہ کوشش کریں۔',
  'No phone or messaging app is available on this device.':
      'اس آلے میں کال یا پیغام بھیجنے کی ایپ دستیاب نہیں۔',
  'Fill this field': 'یہ خانہ مکمل کریں',
  'Enter your name': 'اپنا نام لکھیں',
  'Enter a name': 'نام لکھیں',
  'Enter the worker name': 'کاریگر کا نام لکھیں',
  'Enter your city': 'اپنا شہر لکھیں',
  'Enter a valid phone number': 'درست فون نمبر لکھیں',
  'Enter a valid rupee amount': 'روپوں میں درست رقم لکھیں',
  'Enter experience from 0 to 60 years': '۰ سے ۶۰ سال تک تجربہ لکھیں',
  'Choose a service': 'خدمت چنیں',
  'Enter the work address': 'کام کا پتہ لکھیں',
  'Details are too long': 'تفصیل بہت طویل ہے',
  'Notes are too long': 'نوٹس بہت طویل ہیں',
  'Choose a valid date': 'درست تاریخ چنیں',
  'Choose a future date and time': 'آنے والی تاریخ اور وقت چنیں',
  'The worker contact was removed. Choose another contact.':
      'کاریگر کا رابطہ حذف ہو گیا ہے۔ دوسرا رابطہ چنیں۔',
  'You already have this appointment. Choose another time.':
      'اس وقت پہلے سے ملاقات محفوظ ہے۔ دوسرا وقت چنیں۔',
  'This job was removed': 'یہ کام حذف ہو گیا ہے',
  'Create your profile first': 'پہلے اپنی پروفائل بنائیں',
  'Open your phone data before saving': 'محفوظ کرنے سے پہلے فون کا ڈیٹا کھولیں',
  'Could not save to your phone. Check device storage and try again.':
      'فون میں محفوظ نہیں ہوا۔ فون کی اسٹوریج چیک کرکے دوبارہ کوشش کریں۔',
  'Could not complete this action. Please try again.':
      'یہ عمل مکمل نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
  'Phone storage needs attention': 'فون کی اسٹوریج چیک کریں',
  'Try again': 'دوبارہ کوشش کریں',
  'Your saved phone data could not be opened. Check device storage, then try again.':
      'فون کا محفوظ ڈیٹا نہیں کھل سکا۔ فون کی اسٹوریج چیک کرکے دوبارہ کوشش کریں۔',
  'Recovered your records from the last saved copy.':
      'آپ کے ریکارڈ آخری محفوظ نقل سے بحال ہو گئے۔',
  'Language could not be saved. Please try again.':
      'زبان محفوظ نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
  'This page is unavailable': 'یہ صفحہ دستیاب نہیں',
  'Return to your dashboard to continue.':
      'آگے بڑھنے کے لیے اپنے ڈیش بورڈ پر واپس جائیں۔',
  'Return home': 'ہوم پر جائیں',
  'Start with your profile': 'اپنی پروفائل سے شروع کریں',
  'Choose Worker or Work giver, add your name and city, and save your profile.':
      'کاریگر یا کام دینے والا چنیں، اپنا نام اور شہر لکھیں اور پروفائل محفوظ کریں۔',
  'Keep useful contacts': 'کارآمد رابطے محفوظ کریں',
  'Add workers you know. Search by name, city or service in English, Urdu or Roman Urdu.':
      'اپنے جاننے والے کاریگر شامل کریں۔ نام، شہر یا خدمت کو انگریزی، اردو یا رومن اردو میں تلاش کریں۔',
  'Plan and track work': 'کام طے کریں اور پیش رفت دیکھیں',
  'Save a job with a date, time, address and price. Update its status as the work progresses.':
      'کام کی تاریخ، وقت، پتہ اور قیمت محفوظ کریں۔ کام کی پیش رفت کے ساتھ حالت تبدیل کریں۔',
  'Agree directly': 'براہِ راست کام طے کریں',
  'Call, send SMS or share your request. A saved appointment does not notify another person or reserve their time.':
      'کال کریں، ایس ایم ایس بھیجیں یا درخواست شیئر کریں۔ فون میں ملاقات محفوظ کرنے سے دوسرے شخص کو اطلاع نہیں جاتی اور اس کا وقت بک نہیں ہوتا۔',
  'Your phone, your records': 'آپ کا فون، آپ کے ریکارڈ',
  'Khidmat works without an online account. Profiles, contacts and jobs are stored on this phone and do not sync to other phones.':
      'خدمت آن لائن اکاؤنٹ کے بغیر کام کرتی ہے۔ پروفائل، رابطے اور کام اسی فون میں محفوظ ہوتے ہیں اور دوسرے فون پر خود نہیں جاتے۔',
  'Keep a backup': 'بیک اپ محفوظ رکھیں',
  'Use Backup and restore before changing phones or uninstalling the app.':
      'فون بدلنے یا ایپ حذف کرنے سے پہلے بیک اپ اور بحالی استعمال کریں۔',
  'Phone and SMS': 'کال اور ایس ایم ایس',
  'The Call and Send SMS buttons open your phone’s dialer and messaging app. Your mobile provider’s usual charges apply.':
      'کال اور ایس ایم ایس کے بٹن فون کی متعلقہ ایپ کھولتے ہیں۔ آپ کی موبائل کمپنی کے معمول کے چارجز لاگو ہوتے ہیں۔',
  'Shared online services': 'مشترکہ آن لائن سہولتیں',
  'Shared worker discovery, OTP login and in-app live chat need an online service. They are not enabled in this version.':
      'مشترکہ کاریگروں کی تلاش، او ٹی پی لاگ اِن اور ایپ میں براہِ راست چیٹ کے لیے آن لائن سہولت درکار ہے۔ یہ سہولتیں اس ورژن میں فعال نہیں۔',
};
