-- Configurable catalog, not sample workers/accounts. UUIDs remain stable.
begin;
insert into public.professions(id,category,name,name_ur,skills,questions,sort_order) values
('10000000-0000-4000-8000-000000000001','Construction','Mazdoor','مزدور','["General Labourer","Construction Helper","Material Handling","Site Cleaning"]',
 '[{"key":"role","label":"Construction role","type":"select","required":true,"options":["Labourer","Helper","Team leader"]},{"key":"work_types","label":"Types of work","type":"multiselect","required":true,"options":["Material handling","Digging","Concrete mixing","Site cleaning"]},{"key":"team","label":"Can join a team","type":"boolean","required":false}]',1),
('10000000-0000-4000-8000-000000000002','Construction','Mason','مستری','["Brickwork","Plastering","Concrete Work","Boundary Walls"]',
 '[{"key":"work_types","label":"Masonry specializations","type":"multiselect","required":true,"options":["Brickwork","Plastering","Concrete work","Boundary walls"]},{"key":"team","label":"Can bring helpers","type":"boolean","required":false}]',2),
('10000000-0000-4000-8000-000000000003','Electrical Services','Electrician','الیکٹریشن','["Wiring Repair","Wiring Installation","Fault Finding","Switchboard Installation","Solar Wiring"]',
 '[{"key":"setting","label":"Work settings","type":"multiselect","required":true,"options":["Residential","Commercial","Industrial"]},{"key":"services","label":"Electrical capabilities","type":"multiselect","required":true,"options":["Wiring","Installation","Troubleshooting","Switchboards","Solar wiring"]},{"key":"qualification","label":"Relevant qualifications (optional)","type":"text","required":false}]',3),
('10000000-0000-4000-8000-000000000004','Plumbing Services','Plumber','پلمبر','["Leakage Repair","Pipe Installation","Bathroom Installation","Kitchen Plumbing","Drain Cleaning"]',
 '[{"key":"services","label":"Plumbing services","type":"multiselect","required":true,"options":["Pipe installation","Leakage repair","Bathroom installation","Kitchen installation","Drain cleaning"]},{"key":"emergency","label":"Offers emergency appointments","type":"boolean","required":false}]',4),
('10000000-0000-4000-8000-000000000005','Home Services','Painter','پینٹر','["Interior Painting","Exterior Painting","Surface Preparation","Spray Painting","Wall Finishing"]',
 '[{"key":"setting","label":"Painting work","type":"multiselect","required":true,"options":["Interior","Exterior","Both"]},{"key":"techniques","label":"Specializations","type":"multiselect","required":false,"options":["Surface preparation","Spray painting","Texture finishing","Wood finishing"]}]',5),
('10000000-0000-4000-8000-000000000006','Home Services','Carpenter','بڑھئی','["Furniture Repair","Doors and Windows","Kitchen Cabinets","Custom Furniture"]',
 '[{"key":"materials","label":"Materials worked with","type":"multiselect","required":true,"options":["Solid wood","Plywood","MDF","Laminates"]}]',6),
('10000000-0000-4000-8000-000000000007','Construction','Welder','ویلڈر','["Gate Fabrication","Grills and Railings","Metal Repair","Steel Structures"]',
 '[{"key":"methods","label":"Welding methods","type":"multiselect","required":true,"options":["Arc welding","MIG","TIG","Gas welding"]}]',7),
('10000000-0000-4000-8000-000000000008','Construction','Tile Installer','ٹائل لگانے والا','["Floor Tiles","Wall Tiles","Bathroom Tiling","Tile Repair"]',
 '[{"key":"materials","label":"Tile materials","type":"multiselect","required":true,"options":["Ceramic","Porcelain","Marble","Granite"]}]',8),
('10000000-0000-4000-8000-000000000009','Appliance Services','AC Technician','اے سی ٹیکنیشن','["AC Installation","AC Repair","AC Servicing","Refrigerator Repair"]',
 '[{"key":"services","label":"Technician services","type":"multiselect","required":true,"options":["Installation","Repair","Maintenance"]},{"key":"equipment","label":"Supported equipment","type":"multiselect","required":true,"options":["Split AC","Window AC","Inverter AC","Refrigerator","Freezer"]}]',9),
('10000000-0000-4000-8000-000000000010','Home Services','Cleaner','صفائی کرنے والا','["House Cleaning","Deep Cleaning","Office Cleaning","Water Tank Cleaning"]',
 '[{"key":"supplies","label":"Brings cleaning supplies","type":"boolean","required":false},{"key":"settings","label":"Cleaning settings","type":"multiselect","required":true,"options":["Homes","Offices","Shops","Water tanks"]}]',10),
('10000000-0000-4000-8000-000000000011','Outdoor Services','Gardener','مالی','["Garden Maintenance","Lawn Care","Planting","Tree Pruning"]',
 '[{"key":"tools","label":"Brings gardening tools","type":"boolean","required":false}]',11),
('10000000-0000-4000-8000-000000000012','Appliance Services','Appliance Repair Technician','گھریلو آلات کی مرمت','["Washing Machine Repair","Oven Repair","Water Pump Repair","Small Appliance Repair"]',
 '[{"key":"appliances","label":"Supported appliances","type":"multiselect","required":true,"options":["Washing machines","Ovens","Water pumps","Small appliances"]}]',12),
('10000000-0000-4000-8000-000000000013','Home Services','Domestic Helper','گھریلو مددگار','["Household Help","Cooking","Laundry","Part Time Help"]',
 '[{"key":"tasks","label":"Household tasks offered","type":"multiselect","required":true,"options":["Household cleaning","Cooking","Laundry","Ironing"]},{"key":"schedule","label":"Preferred work arrangement","type":"select","required":true,"options":["Part time","Full time","Occasional"]}]',13),
('10000000-0000-4000-8000-000000000014','Electrical Services','Solar Technician','سولر ٹیکنیشن','["Solar Installation","Panel Cleaning","Inverter Maintenance","Solar Fault Finding"]',
 '[{"key":"systems","label":"Systems supported","type":"multiselect","required":true,"options":["On grid","Off grid","Hybrid"]}]',14),
('10000000-0000-4000-8000-000000000015','Home Services','Pest Control Technician','کیڑوں کا خاتمہ','["Termite Treatment","Cockroach Control","General Pest Control"]',
 '[{"key":"services","label":"Treatments offered","type":"multiselect","required":true,"options":["Termites","Cockroaches","General pests"]},{"key":"qualification","label":"Relevant training (optional)","type":"text","required":false}]',15),
('10000000-0000-4000-8000-000000000016','Learning Services','Tutor','استاد','["Primary Subjects","Mathematics","English","Science","Computer Skills"]',
 '[{"key":"levels","label":"Levels taught","type":"multiselect","required":true,"options":["Primary","Middle","Secondary","College","Adult learning"]}]',16),
('10000000-0000-4000-8000-000000000017','Personal Services','Beautician','بیوٹیشن','["Hair Styling","Makeup","Skin Care","Bridal Services"]',
 '[{"key":"setting","label":"Service setting","type":"select","required":true,"options":["At customer location","At salon","Both"]}]',17),
('10000000-0000-4000-8000-000000000018','Other Services','Other Local Service','دیگر مقامی خدمات','["Other Local Service"]',
 '[{"key":"service","label":"Describe your service","type":"text","required":true}]',99);
commit;
